// AI Trend Tracker — auto-generated 2026-06-28 01:08:10
// DO NOT edit manually — re-run fetch_ai_news.py to refresh
const ARTICLES_DATA = {
  "last_updated": "2026-06-28T01:08:10.011217+00:00",
  "total": 95,
  "articles": [
    {
      "id": "05c25aefe5ad",
      "title": "US AI stock sell-off shakes markets from Wall Street to Asia",
      "url": "https://www.theguardian.com/business/2026/jun/23/ai-stocks-sell-off-us-markets",
      "source": "Hacker News",
      "source_type": "community",
      "published": "2026-06-24T03:36:50+00:00",
      "summary": "⬆ 41 points · 19 comments on Hacker News",
      "category": "Big Tech News",
      "color": "#ff6600"
    },
    {
      "id": "3b011618a4b8",
      "title": "DiffusionBench: Towards Holistic Evaluation of Generative Diffusion Transformers",
      "url": "https://github.com/End2End-Diffusion/diffusion-bench",
      "source": "Hacker News",
      "source_type": "community",
      "published": "2026-06-24T02:12:31+00:00",
      "summary": "⬆ 33 points · 1 comments on Hacker News",
      "category": "Models & Research",
      "color": "#ff6600"
    },
    {
      "id": "87e972a2730e",
      "title": "NVIDIA and AWS Collaborate to Bring AI to Production at Scale",
      "url": "https://blogs.nvidia.com/blog/nvidia-aws-ai-production-scale/",
      "source": "NVIDIA",
      "source_type": "company",
      "published": "2026-06-24T00:05:37+00:00",
      "summary": "Building AI systems at scale is demanding, requiring low-latency inference, fast vector search, strong GPU price-performance and infrastructure that can grow without multiplying operational complexity. NVIDIA’s latest work with Amazon Web Services (AWS) addresses each of those...",
      "category": "Real-world AI Use",
      "color": "#76b900"
    },
    {
      "id": "41e29831de85",
      "title": "India’s MoEngage bets that the future of marketing is millions of AI agents",
      "url": "https://techcrunch.com/2026/06/23/indias-moengage-bets-marketings-future-on-millions-of-ai-agents/",
      "source": "TechCrunch",
      "source_type": "news",
      "published": "2026-06-23T23:30:00+00:00",
      "summary": "The all-cash deal gives MoEngage access to technology that assigns AI agents to individual customers.",
      "category": "Funding & Business",
      "color": "#0d9488"
    },
    {
      "id": "f7f8b49c4475",
      "title": "White House drastically shortens deadline for dropping quantum-vulnerable crypto",
      "url": "https://arstechnica.com/information-technology/2026/06/executive-order-bumps-up-deadline-to-move-off-quantum-vulnerable-crypto/",
      "source": "Ars Technica",
      "source_type": "news",
      "published": "2026-06-23T22:30:57+00:00",
      "summary": "Order warns of national security risks if post-quantum cryptography isn't adopted in time.",
      "category": "Policy & Safety",
      "color": "#ff6600"
    },
    {
      "id": "c7b57177e881",
      "title": "Trains halted across Germany because of communication system problem",
      "url": "https://apnews.com/article/germany-trains-halted-communications-radio-problem-deutsche-bahn-e8fd970b2d889f3ae7ce03322d5c726b",
      "source": "Hacker News",
      "source_type": "community",
      "published": "2026-06-23T21:19:44+00:00",
      "summary": "⬆ 161 points · 154 comments on Hacker News",
      "category": "Big Tech News",
      "color": "#ff6600"
    },
    {
      "id": "9ab4e89c7489",
      "title": "Heads in the game",
      "url": "https://www.technologyreview.com/2026/06/23/1138214/heads-in-the-game/",
      "source": "MIT Tech Review",
      "source_type": "news",
      "published": "2026-06-23T21:00:00+00:00",
      "summary": "The Argentina v. France final of the 2022 Men’s World Cup in Qatar was shaping up to be one of the most epic games in soccer history. With just 12 minutes remaining in the extra time added to the game to break a tie, the referee had a critical decision to make—and fast. Lionel...",
      "category": "Big Tech News",
      "color": "#b91c1c"
    },
    {
      "id": "cab8cc49d4c1",
      "title": "Super Mario is mathier than you think",
      "url": "https://www.technologyreview.com/2026/06/23/1138262/super-mario-is-mathier-than-you-think/",
      "source": "MIT Tech Review",
      "source_type": "news",
      "published": "2026-06-23T21:00:00+00:00",
      "summary": "Here’s a problem you probably didn’t solve in school: You’re an ambitious young plumber from Brooklyn in a world inhabited by violent human-size mushrooms called Goombas. The love of your life has been kidnapped, so you embark on a quest to rescue her, venturing through stretc...",
      "category": "Big Tech News",
      "color": "#b91c1c"
    },
    {
      "id": "251d7d3c7855",
      "title": "A man of many words",
      "url": "https://www.technologyreview.com/2026/06/23/1138267/a-man-of-many-words/",
      "source": "MIT Tech Review",
      "source_type": "news",
      "published": "2026-06-23T21:00:00+00:00",
      "summary": "Brian Sietsema has a favorite word. It’s somewhat surprising that he can choose just one. He’s the person spellers rely on to confirm pronunciations and answer questions about the roots of the words they’re given at the Scripps National Spelling Bee—arguably the world’s most p...",
      "category": "Big Tech News",
      "color": "#b91c1c"
    },
    {
      "id": "d5c7b562dcef",
      "title": "Sharing a love for calculus",
      "url": "https://www.technologyreview.com/2026/06/23/1138271/sharing-a-love-for-calculus/",
      "source": "MIT Tech Review",
      "source_type": "news",
      "published": "2026-06-23T21:00:00+00:00",
      "summary": "The national conversation about the value of education is currently dominated by speculation about the risks and positive potential of AI. Whatever your own perspective on that debate, I hope you’ll be glad to know that MIT is also working on a deeply important but comparative...",
      "category": "Real-world AI Use",
      "color": "#b91c1c"
    },
    {
      "id": "22a3e516196e",
      "title": "Stand Up for Research, Innovation, and Education",
      "url": "https://www.technologyreview.com/2026/06/23/1138274/stand-up-for-research-innovation-and-education-6/",
      "source": "MIT Tech Review",
      "source_type": "news",
      "published": "2026-06-23T21:00:00+00:00",
      "summary": "Right now, MIT alumni and friends are voicing their support for: America’s scientific and technological leadership Merit-based admissions and affordable education Advances that increase US health, security, and prosperity Our community is standing up for MIT and its mission to...",
      "category": "Real-world AI Use",
      "color": "#b91c1c"
    },
    {
      "id": "f1b89e0e6dff",
      "title": "Ultrasound imaging turns a robot hand into a skillful mimic",
      "url": "https://www.technologyreview.com/2026/06/23/1138279/ultrasound-imaging-turns-a-robot-hand-into-a-skillful-mimic/",
      "source": "MIT Tech Review",
      "source_type": "news",
      "published": "2026-06-23T21:00:00+00:00",
      "summary": "Our hands are the nimblest parts of our bodies, coordinating 34 muscles, 27 joints, and over 100 tendons and ligaments to perform countless nuanced movements and gestures. So far, robots have been notoriously bad at mimicking that dexterity, in part because researchers struggl...",
      "category": "Big Tech News",
      "color": "#b91c1c"
    },
    {
      "id": "bc3c63ee108a",
      "title": "Reinventing the zipper",
      "url": "https://www.technologyreview.com/2026/06/23/1138282/reinventing-the-zipper/",
      "source": "MIT Tech Review",
      "source_type": "news",
      "published": "2026-06-23T21:00:00+00:00",
      "summary": "With an adaptable fastener designed at CSAIL, pitching a tent or adjusting the cast for a broken bone could be almost as easy as zipping your coat. The researchers, led by associate professor Stefanie Mueller, were inspired by an abandoned prototype for a three-sided zipper th...",
      "category": "Policy & Safety",
      "color": "#b91c1c"
    },
    {
      "id": "4024d2a89819",
      "title": "Engineered “mini livers” could be injected as an alternative to transplantation",
      "url": "https://www.technologyreview.com/2026/06/23/1138285/engineered-mini-livers-could-be-injected-as-an-alternative-to-transplantation/",
      "source": "MIT Tech Review",
      "source_type": "news",
      "published": "2026-06-23T21:00:00+00:00",
      "summary": "A technology developed by Professor Sangeeta Bhatia, SM ’93, PhD ’97, and colleagues could offer new hope to the thousands of Americans with chronic liver disease who are waiting for an organ transplant or not strong enough to tolerate one. The liver is involved in regulating ...",
      "category": "Big Tech News",
      "color": "#b91c1c"
    },
    {
      "id": "f77313f8cbfa",
      "title": "Plants appear to detect the patter of falling rain",
      "url": "https://www.technologyreview.com/2026/06/23/1138288/plants-appear-to-detect-the-patter-of-falling-rain/",
      "source": "MIT Tech Review",
      "source_type": "news",
      "published": "2026-06-23T21:00:00+00:00",
      "summary": "MIT engineers have found the first direct evidence that plant seeds can sense sounds in nature: Rice submerged in shallow water germinated 30% to 40% more quickly when exposed to vibrations from water dripping on the surface. They think other types of seeds may respond similar...",
      "category": "Big Tech News",
      "color": "#b91c1c"
    },
    {
      "id": "d8a8b21ee539",
      "title": "A breath test could diagnose pneumonia in minutes",
      "url": "https://www.technologyreview.com/2026/06/23/1138291/a-breath-test-could-diagnose-pneumonia-in-minutes/",
      "source": "MIT Tech Review",
      "source_type": "news",
      "published": "2026-06-23T21:00:00+00:00",
      "summary": "With a test being developed at MIT, diagnosing pneumonia and other lung conditions could someday be as easy as breathing into a tube. The test, dubbed PlasmoSniff, is a portable, chip-scale sensor that traps and detects biomarkers, synthetic compounds indicating disease. The i...",
      "category": "Policy & Safety",
      "color": "#b91c1c"
    },
    {
      "id": "7ac8157f1fe1",
      "title": "Don't verify email addresses by sending spam to them",
      "url": "https://milek7.pl/mailverifyspam/",
      "source": "Hacker News",
      "source_type": "community",
      "published": "2026-06-23T20:23:49+00:00",
      "summary": "⬆ 173 points · 52 comments on Hacker News",
      "category": "Big Tech News",
      "color": "#ff6600"
    },
    {
      "id": "cbf9487549c8",
      "title": "Orion 1.1 for macOS is out, with containers",
      "url": "https://orionbrowser.com/updates/versions/1.1",
      "source": "Hacker News",
      "source_type": "community",
      "published": "2026-06-23T20:22:41+00:00",
      "summary": "⬆ 32 points · 0 comments on Hacker News",
      "category": "Big Tech News",
      "color": "#ff6600"
    },
    {
      "id": "1170c2dc2174",
      "title": "Oracle’s 21,000 layoffs help drive its debt-fueled AI investments",
      "url": "https://arstechnica.com/ai/2026/06/oracles-21000-layoffs-help-drive-its-debt-fueled-ai-investments/",
      "source": "Ars Technica",
      "source_type": "news",
      "published": "2026-06-23T20:17:38+00:00",
      "summary": "Oracle is spending billions on data center infrastructure to support AI.",
      "category": "Tools & Stack",
      "color": "#ff6600"
    },
    {
      "id": "58fe011fb627",
      "title": "Show HN: RLM-based local debugger for AI agent traces",
      "url": "https://github.com/context-labs/halo",
      "source": "Hacker News",
      "source_type": "community",
      "published": "2026-06-23T18:21:52+00:00",
      "summary": "⬆ 19 points · 7 comments on Hacker News",
      "category": "Big Tech News",
      "color": "#ff6600"
    },
    {
      "id": "1948945ee980",
      "title": "How GPT-5 helped immunologist Derya Unutmaz solve a 3-year-old mystery",
      "url": "https://openai.com/index/gpt-5-immunology-mystery",
      "source": "OpenAI",
      "source_type": "company",
      "published": "2026-06-23T17:00:00+00:00",
      "summary": "GPT-5 Pro helped solve a 3-year-old immunology mystery, offering insights into T cell behavior. The breakthrough could support cancer and autoimmune research.",
      "category": "Models & Research",
      "color": "#10a37f"
    },
    {
      "id": "492604e8457d",
      "title": "Anthropic’s Claude Tag is learning your company, one Slack message at a time",
      "url": "https://techcrunch.com/2026/06/23/anthropics-claude-tag-is-learning-your-company-one-slack-message-at-a-time/",
      "source": "TechCrunch",
      "source_type": "news",
      "published": "2026-06-23T17:00:00+00:00",
      "summary": "Anthropic’s new Claude Tag brings an always-on AI teammate to Slack. But beyond productivity, the feature is a strategic play to capture organizational context, institutional knowledge, and enterprise workflows.",
      "category": "Models & Research",
      "color": "#0d9488"
    },
    {
      "id": "c49e0b9bdaf3",
      "title": "Build a protein research copilot with Amazon Bedrock AgentCore",
      "url": "https://aws.amazon.com/blogs/machine-learning/build-a-protein-research-copilot-with-amazon-bedrock-agentcore/",
      "source": "AWS ML",
      "source_type": "company",
      "published": "2026-06-23T16:39:34+00:00",
      "summary": "This post shows you how to build a conversational protein research assistant that combines three capabilities: Natural language query parsing to extract structured search parameters, vector similarity search over protein embeddings using a specialized language model and ai-gen...",
      "category": "Models & Research",
      "color": "#ff9900"
    },
    {
      "id": "2e7fd44e7f72",
      "title": "Shared infrastructure, isolated tenants: Pool model multi-tenancy with Amazon Bedrock AgentCore",
      "url": "https://aws.amazon.com/blogs/machine-learning/shared-infrastructure-isolated-tenants-pool-model-multi-tenancy-with-amazon-bedrock-agentcore/",
      "source": "AWS ML",
      "source_type": "company",
      "published": "2026-06-23T15:43:59+00:00",
      "summary": "In this post, you will learn patterns for implementing production-ready multi-tenant systems using Amazon Bedrock AgentCore. You will see these patterns demonstrated through healthcare AI agents that serve multiple clinics and hospitals.",
      "category": "Models & Research",
      "color": "#ff9900"
    },
    {
      "id": "41db22d041bb",
      "title": "AI's Affordability Crisis",
      "url": "https://blog.dshr.org/2026/06/ais-affordability-crisis.html",
      "source": "Hacker News",
      "source_type": "community",
      "published": "2026-06-23T15:11:17+00:00",
      "summary": "⬆ 284 points · 375 comments on Hacker News",
      "category": "Big Tech News",
      "color": "#ff6600"
    },
    {
      "id": "5bf2bc3dc618",
      "title": "Mistral OCR 4",
      "url": "https://mistral.ai/news/ocr-4/",
      "source": "Hacker News",
      "source_type": "community",
      "published": "2026-06-23T14:03:19+00:00",
      "summary": "⬆ 465 points · 121 comments on Hacker News",
      "category": "Models & Research",
      "color": "#ff6600"
    },
    {
      "id": "aca01865fd76",
      "title": "4 days left to save up to $190 on TechCrunch Founder Summit 2026",
      "url": "https://techcrunch.com/2026/06/23/4-days-left-to-save-up-to-190-on-techcrunch-founder-summit-2026/",
      "source": "TechCrunch",
      "source_type": "news",
      "published": "2026-06-23T14:00:00+00:00",
      "summary": "Four days left to save up to $190 on your pass to TechCrunch Founder Summit 2026 — the ultimate founder bootcamp — before Early Bird rates end on June 26 at 11:59 p.m. PT. Register today.",
      "category": "Big Tech News",
      "color": "#0d9488"
    },
    {
      "id": "cea555c8dbfd",
      "title": "Madison Square Garden compiled a list of activists against facial recognition",
      "url": "https://www.404media.co/madison-square-garden-made-dossier-on-activists-who-opposed-facial-recognition/",
      "source": "Hacker News",
      "source_type": "community",
      "published": "2026-06-23T13:36:10+00:00",
      "summary": "⬆ 301 points · 88 comments on Hacker News",
      "category": "Big Tech News",
      "color": "#ff6600"
    },
    {
      "id": "942fad7ac452",
      "title": "How Businesses Are Building Specialized AI They Can Trust",
      "url": "https://blogs.nvidia.com/blog/nvidia-agent-toolkit-open-models-tools-skills-secure-runtime-ai-agents/",
      "source": "NVIDIA",
      "source_type": "company",
      "published": "2026-06-23T13:00:07+00:00",
      "summary": "Companies are asking how to build specialized AI that fits with the way their workflows actually run. The first wave of enterprise AI was about access. Companies experimented with new frontier and open models, ran pilots and explored how AI can help. Now, specialized agents — ...",
      "category": "Models & Research",
      "color": "#76b900"
    },
    {
      "id": "1b1b1aa40d91",
      "title": "Helping build shared standards for advanced AI",
      "url": "https://openai.com/index/helping-build-shared-standards-for-advanced-ai",
      "source": "OpenAI",
      "source_type": "company",
      "published": "2026-06-23T13:00:00+00:00",
      "summary": "OpenAI helps build shared standards for advanced AI, supporting evaluation frameworks, safety practices, and global cooperation through the Appia Foundation.",
      "category": "Tools & Stack",
      "color": "#10a37f"
    },
    {
      "id": "6ad2703ed5c3",
      "title": "Fika Jobs raises $4M to build a video-first hiring platform where AI agents interview candidates",
      "url": "https://techcrunch.com/2026/06/23/fika-jobs-raises-4m-to-build-a-video-first-hiring-platform-where-ai-agents-interview-candidates/",
      "source": "TechCrunch",
      "source_type": "news",
      "published": "2026-06-23T13:00:00+00:00",
      "summary": "Stockholm-based startup Fika Jobs is building a video-first hiring platform that combines AI interview agents with short-form video profiles, creating something that feels like a cross between LinkedIn and TikTok.",
      "category": "Tools & Stack",
      "color": "#0d9488"
    },
    {
      "id": "237e7c87455b",
      "title": "Build real agentic apps using CUGA: two dozen working examples on a lightweight harness",
      "url": "https://huggingface.co/blog/ibm-research/cuga-apps",
      "source": "Hugging Face",
      "source_type": "company",
      "published": "2026-06-23T12:51:55+00:00",
      "summary": "",
      "category": "Big Tech News",
      "color": "#e9a800"
    },
    {
      "id": "2859bfe773c9",
      "title": "The Low-Tech AI of Elden Ring",
      "url": "https://nega.tv/posts/low-tech-ai-of-elden-ring.html",
      "source": "Hacker News",
      "source_type": "community",
      "published": "2026-06-23T11:40:50+00:00",
      "summary": "⬆ 145 points · 79 comments on Hacker News",
      "category": "Big Tech News",
      "color": "#ff6600"
    },
    {
      "id": "eeb4f35cb8d6",
      "title": "Apple is going to raise device prices, but when?",
      "url": "https://daringfireball.net/linked/2026/06/22/apple-device-prices-when",
      "source": "Hacker News",
      "source_type": "community",
      "published": "2026-06-23T10:54:56+00:00",
      "summary": "⬆ 104 points · 82 comments on Hacker News",
      "category": "Big Tech News",
      "color": "#ff6600"
    },
    {
      "id": "5669b8cec957",
      "title": "NVIDIA Powers Over 400 of the World’s 500 Fastest Supercomputers",
      "url": "https://blogs.nvidia.com/blog/top500-green500-supercomputers-isc-2026/",
      "source": "NVIDIA",
      "source_type": "company",
      "published": "2026-06-23T09:00:38+00:00",
      "summary": "NVIDIA technologies power more than 400 of the world’s 500 fastest supercomputers — 81% of the TOP500 — according to the latest rankings released this week at the ISC High Performance conference in Hamburg, Germany.",
      "category": "Big Tech News",
      "color": "#76b900"
    },
    {
      "id": "65171448dd1f",
      "title": "AI Built a Nuke and Still Lost",
      "url": "https://www.lwilko.com/blog/i-gave-an-ai-a-civilization",
      "source": "Hacker News",
      "source_type": "community",
      "published": "2026-06-23T08:16:45+00:00",
      "summary": "⬆ 9 points · 0 comments on Hacker News",
      "category": "Big Tech News",
      "color": "#ff6600"
    },
    {
      "id": "25c535f50064",
      "title": "How sad should I be about ChatGPT? (2022)",
      "url": "https://robertheaton.com/chatgpt/",
      "source": "Hacker News",
      "source_type": "community",
      "published": "2026-06-23T07:52:03+00:00",
      "summary": "⬆ 4 points · 0 comments on Hacker News",
      "category": "Models & Research",
      "color": "#ff6600"
    },
    {
      "id": "deedb0177c68",
      "title": "The new HTTP QUERY method explained",
      "url": "https://kreya.app/blog/new-http-query-method-explained/",
      "source": "Hacker News",
      "source_type": "community",
      "published": "2026-06-23T06:05:37+00:00",
      "summary": "⬆ 64 points · 30 comments on Hacker News",
      "category": "Big Tech News",
      "color": "#ff6600"
    },
    {
      "id": "de8964e17252",
      "title": "NVIDIA Brings Trusted, 24/7 AI Agents to Telecom Operations",
      "url": "https://blogs.nvidia.com/blog/telecom-ai-agents-dtw-ignite-2026/",
      "source": "NVIDIA",
      "source_type": "company",
      "published": "2026-06-23T06:00:09+00:00",
      "summary": "Telecom operators have seen remarkable returns from using generative AI to automate network management, customer care and back-office operations. Most of that impact has been task‑based: automation that speeds up predetermined steps while people manually correlate insights and...",
      "category": "Real-world AI Use",
      "color": "#76b900"
    },
    {
      "id": "cab23dbbd064",
      "title": "OpenAI DayBreak – GPT-5.5-Cyber",
      "url": "https://openai.com/index/daybreak-securing-the-world/",
      "source": "Hacker News",
      "source_type": "community",
      "published": "2026-06-23T01:36:08+00:00",
      "summary": "⬆ 84 points · 40 comments on Hacker News",
      "category": "Models & Research",
      "color": "#ff6600"
    },
    {
      "id": "44208f99c618",
      "title": "The running list: major tech layoffs in 2026 where employers cited AI",
      "url": "https://techcrunch.com/2026/06/22/the-running-list-major-tech-layoffs-in-2026-where-employers-cited-ai/",
      "source": "TechCrunch",
      "source_type": "news",
      "published": "2026-06-23T01:27:55+00:00",
      "summary": "A running look — in reverse chronological order — at the bigger tech companies that have announced significant layoffs this year with AI as a stated factor.",
      "category": "Big Tech News",
      "color": "#0d9488"
    },
    {
      "id": "d4b0a5576fde",
      "title": "In praise of memcached",
      "url": "https://jchri.st/blog/in-praise-of-memcached/",
      "source": "Hacker News",
      "source_type": "community",
      "published": "2026-06-23T01:15:05+00:00",
      "summary": "⬆ 141 points · 55 comments on Hacker News",
      "category": "Big Tech News",
      "color": "#ff6600"
    },
    {
      "id": "8bdf35b5ee90",
      "title": "OpenAI launches new initiative to help find and patch open source bugs",
      "url": "https://techcrunch.com/2026/06/22/openai-launches-new-initiative-to-help-find-and-patch-open-source-bugs/",
      "source": "TechCrunch",
      "source_type": "news",
      "published": "2026-06-23T00:11:31+00:00",
      "summary": "OpenAI is using AI to help the open source community better protect itself.",
      "category": "Big Tech News",
      "color": "#0d9488"
    },
    {
      "id": "350becd7dc0b",
      "title": "How Omio is building the future of conversational travel",
      "url": "https://openai.com/index/omio",
      "source": "OpenAI",
      "source_type": "company",
      "published": "2026-06-23T00:00:00+00:00",
      "summary": "Discover how Omio uses OpenAI to power conversational travel experiences, accelerate product development, and transform into an AI-native company.",
      "category": "Big Tech News",
      "color": "#10a37f"
    },
    {
      "id": "e9e69e179378",
      "title": "Shipping huggingface_hub every week with AI, open tools, and a human in the loop",
      "url": "https://huggingface.co/blog/huggingface-hub-release-ci",
      "source": "Hugging Face",
      "source_type": "company",
      "published": "2026-06-23T00:00:00+00:00",
      "summary": "",
      "category": "Tools & Stack",
      "color": "#e9a800"
    },
    {
      "id": "c144d0a70e05",
      "title": "Experimenting with the proposed Cross-Origin Storage API in Transformers.js",
      "url": "https://huggingface.co/blog/cross-origin-storage",
      "source": "Hugging Face",
      "source_type": "company",
      "published": "2026-06-23T00:00:00+00:00",
      "summary": "",
      "category": "Models & Research",
      "color": "#e9a800"
    },
    {
      "id": "a32d4d3dc25d",
      "title": "Why eval startups fail (2025)",
      "url": "https://thomasliao.com/eval-startups",
      "source": "Hacker News",
      "source_type": "community",
      "published": "2026-06-22T23:20:53+00:00",
      "summary": "⬆ 9 points · 1 comments on Hacker News",
      "category": "Funding & Business",
      "color": "#ff6600"
    },
    {
      "id": "d8601afd6862",
      "title": "Meta pauses AI training program tracking employee keystrokes after internal leak",
      "url": "https://www.businessinsider.com/meta-ai-training-data-leak-exposed-employee-activity-across-company-2026-6",
      "source": "Hacker News",
      "source_type": "community",
      "published": "2026-06-22T21:43:22+00:00",
      "summary": "⬆ 85 points · 21 comments on Hacker News",
      "category": "Models & Research",
      "color": "#ff6600"
    },
    {
      "id": "c8e3f008a167",
      "title": "Meta Pauses Employee-Tracking Program Following Internal Data Leak",
      "url": "https://www.wired.com/story/meta-pauses-employee-tracking-program-following-internal-security-breach/",
      "source": "Wired",
      "source_type": "news",
      "published": "2026-06-22T21:08:09+00:00",
      "summary": "The move comes after the company left potentially sensitive data from the initiative exposed internally.",
      "category": "Big Tech News",
      "color": "#6b7280"
    },
    {
      "id": "f811b25fbf9d",
      "title": "The AI world is getting ‘loopy’",
      "url": "https://techcrunch.com/2026/06/22/the-ai-world-is-getting-loopy/",
      "source": "TechCrunch",
      "source_type": "news",
      "published": "2026-06-22T20:53:11+00:00",
      "summary": "The loop takes agentic AI a step further by authorizing a swarm of agents to work continuously in the background, endlessly.",
      "category": "Big Tech News",
      "color": "#0d9488"
    },
    {
      "id": "b371e572d377",
      "title": "Meta Exposed Data Internally From Its Controversial Employee-Tracking Program",
      "url": "https://www.wired.com/story/meta-accidentally-let-employees-access-each-others-keystroke-data/",
      "source": "Wired",
      "source_type": "news",
      "published": "2026-06-22T20:28:53+00:00",
      "summary": "Employees had previously raised concerns about the initiative, which involves collecting workers’ keystroke data to train AI models.",
      "category": "Models & Research",
      "color": "#6b7280"
    },
    {
      "id": "a9ba7814c8ed",
      "title": "AI chipmaker Groq confirms $650M raise, re-staffs after Nvidia’s $20B not-acqui-hire deal",
      "url": "https://techcrunch.com/2026/06/22/ai-chipmaker-groq-confirms-650m-raise-re-staffs-after-nvidias-20b-not-acqui-hire-deal/",
      "source": "TechCrunch",
      "source_type": "news",
      "published": "2026-06-22T20:13:58+00:00",
      "summary": "What does an AI company do after one of those not-acqui-hire deals? Groq raised money, is leaning into its neocloud business, and is hiring new execs.",
      "category": "Big Tech News",
      "color": "#0d9488"
    },
    {
      "id": "e14ed19e3b39",
      "title": "Nvidia wants to cut data center water use, but that’s not the same as fixing AI’s water problem",
      "url": "https://techcrunch.com/2026/06/22/nvidia-wants-to-cut-data-center-water-use-but-thats-not-the-same-as-fixing-ais-water-problem/",
      "source": "TechCrunch",
      "source_type": "news",
      "published": "2026-06-22T20:08:15+00:00",
      "summary": "Nvidia announced a new cooling system that cuts water use inside the data center. But it does nothing to address AI's biggest water use — fossil fuel power plants.",
      "category": "Big Tech News",
      "color": "#0d9488"
    },
    {
      "id": "0bbae9c5d741",
      "title": "Following user outcry, AMD reinstates memory encryption in consumer CPUs",
      "url": "https://arstechnica.com/security/2026/06/following-user-outcry-amd-reinstates-memory-encryption-in-consumer-cpus/",
      "source": "Ars Technica",
      "source_type": "news",
      "published": "2026-06-22T19:16:52+00:00",
      "summary": "Critics saw the move as an underhanded way to steer them toward more costly chips.",
      "category": "Big Tech News",
      "color": "#ff6600"
    },
    {
      "id": "1a31120402af",
      "title": "Canada plans 'nuclear renaissance' with up to 10 reactors built by 2040",
      "url": "https://www.cbc.ca/news/politics/federal-nuclear-strategy-9.7244509",
      "source": "Hacker News",
      "source_type": "community",
      "published": "2026-06-22T19:06:48+00:00",
      "summary": "⬆ 466 points · 314 comments on Hacker News",
      "category": "Big Tech News",
      "color": "#ff6600"
    },
    {
      "id": "2eba6f3aeae1",
      "title": "Google DeepMind bets $75M on AI’s future in Hollywood with A24 deal",
      "url": "https://techcrunch.com/2026/06/22/google-deepmind-bets-75m-on-ais-future-in-hollywood-with-a24-deal/",
      "source": "TechCrunch",
      "source_type": "news",
      "published": "2026-06-22T18:49:44+00:00",
      "summary": "Google DeepMind and A24 are teaming up to build AI filmmaking tools.",
      "category": "Big Tech News",
      "color": "#0d9488"
    },
    {
      "id": "e5321e5c15e4",
      "title": "Three things to watch amid Anthropic’s latest feud with the government",
      "url": "https://www.technologyreview.com/2026/06/22/1139424/three-things-to-watch-amid-anthropics-latest-feud-with-the-government/",
      "source": "MIT Tech Review",
      "source_type": "news",
      "published": "2026-06-22T18:00:00+00:00",
      "summary": "This story originally appeared in The Algorithm, our weekly newsletter on AI. To get stories like this in your inbox first, sign up here. For those of you enjoying your summer unaware of Anthropic’s latest feud with the US government, here’s a recap: In April the company said ...",
      "category": "Policy & Safety",
      "color": "#b91c1c"
    },
    {
      "id": "2854b398bd05",
      "title": "Building pay-per-intelligence for AI agents: How Ampersend uses Amazon Bedrock AgentCore Payments",
      "url": "https://aws.amazon.com/blogs/machine-learning/building-pay-per-intelligence-for-ai-agents-how-ampersend-uses-amazon-bedrock-agentcore-payments/",
      "source": "AWS ML",
      "source_type": "company",
      "published": "2026-06-22T17:53:40+00:00",
      "summary": "In this post, you will learn how Ampersend built a pay-per-intelligence routing layer on top of Amazon Bedrock AgentCore Payments. AI agents autonomously route tasks to the most effective model, pay per request, and operate within spending budgets. You will also see how the tw...",
      "category": "Models & Research",
      "color": "#ff9900"
    },
    {
      "id": "3bc52c088383",
      "title": "Amazon is testing Alexa+ in India with Hindi support",
      "url": "https://techcrunch.com/2026/06/22/amazon-is-testing-alexa-in-india-with-hindi-support/",
      "source": "TechCrunch",
      "source_type": "news",
      "published": "2026-06-22T17:31:29+00:00",
      "summary": "Amazon is planning to increase the footprint of its new conversational AI assistant Alexa+ to India and is inviting users in the country to test out a Hindi-language version.",
      "category": "Big Tech News",
      "color": "#0d9488"
    },
    {
      "id": "33bf1a3e1996",
      "title": "OpenAI Launches Full-Scale Effort to Patch Open-Source Bugs as It Takes on Anthropic’s Mythos",
      "url": "https://www.wired.com/story/openai-launches-full-scale-effort-to-patch-open-source-bugs-as-it-takes-on-anthropics-mythos/",
      "source": "Wired",
      "source_type": "news",
      "published": "2026-06-22T17:00:00+00:00",
      "summary": "Amid concerns about AI models’ cybersecurity capabilities, OpenAI revealed an improved version of GPT-5.5-Cyber and its “Patch the Planet” initiative to fix open-source software bugs.",
      "category": "Models & Research",
      "color": "#6b7280"
    },
    {
      "id": "f7ef68bb6a12",
      "title": "SpaceX inks compute deal with Reflection AI, an open source AI lab",
      "url": "https://techcrunch.com/2026/06/22/spacex-inks-compute-deal-with-reflection-ai-an-open-source-ai-lab/",
      "source": "TechCrunch",
      "source_type": "news",
      "published": "2026-06-22T16:51:29+00:00",
      "summary": "Reflection AI will pay $150 million a month beginning July 1, 2026 through 2029 for immediate access to Nvidia's latest GB300 AI chips and supporting hardware across SpaceX's Colossus 2 data center near Memphis, Tennessee.",
      "category": "Tools & Stack",
      "color": "#0d9488"
    },
    {
      "id": "ffd939d59f3a",
      "title": "Embed the world: Multimodal AI for searchable aerial imagery at scale",
      "url": "https://aws.amazon.com/blogs/machine-learning/embed-the-world-multimodal-ai-for-searchable-aerial-imagery-at-scale/",
      "source": "AWS ML",
      "source_type": "company",
      "published": "2026-06-22T16:32:15+00:00",
      "summary": "In this post, we walk through the problem space, our architecture on Amazon Bedrock and Amazon OpenSearch Serverless, the evaluation methodology we built on OpenStreetMap ground truth, four experiments that compared embedding models, fusion strategies, captioning, and search m...",
      "category": "Models & Research",
      "color": "#ff9900"
    },
    {
      "id": "bc13b5a10356",
      "title": "Running ComfyUI workflows on Amazon SageMaker AI processing jobs",
      "url": "https://aws.amazon.com/blogs/machine-learning/running-comfyui-workflows-on-amazon-sagemaker-ai-processing-jobs/",
      "source": "AWS ML",
      "source_type": "company",
      "published": "2026-06-22T16:28:46+00:00",
      "summary": "In this post, we walk you through how to deploy ComfyUI workflows on Amazon SageMaker AI processing jobs to generate hundreds of high-quality images in a single batch. You learn how to set up the infrastructure using AWS Cloud Development Kit (AWS CDK), configure GPU-accelerat...",
      "category": "Real-world AI Use",
      "color": "#ff9900"
    },
    {
      "id": "f857e1a7ef48",
      "title": "I built Ponytrail, a local audit trail for AI coding-agent edits",
      "url": "https://github.com/0xroylee/ponytrail",
      "source": "Hacker News",
      "source_type": "community",
      "published": "2026-06-22T14:54:59+00:00",
      "summary": "⬆ 18 points · 8 comments on Hacker News",
      "category": "Big Tech News",
      "color": "#ff6600"
    },
    {
      "id": "1a9a5cdd9372",
      "title": "China is having another AI moment",
      "url": "https://www.economist.com/china/2026/06/21/china-is-having-another-ai-moment",
      "source": "Hacker News",
      "source_type": "community",
      "published": "2026-06-22T14:30:47+00:00",
      "summary": "⬆ 9 points · 3 comments on Hacker News",
      "category": "Big Tech News",
      "color": "#ff6600"
    },
    {
      "id": "d509f232d163",
      "title": "The text in Claude Code’s “Extended Thinking” output",
      "url": "https://patrickmccanna.net/the-text-in-claude-codes-extended-thinking-output-is-not-authentic/",
      "source": "Hacker News",
      "source_type": "community",
      "published": "2026-06-22T14:22:46+00:00",
      "summary": "⬆ 301 points · 211 comments on Hacker News",
      "category": "Models & Research",
      "color": "#ff6600"
    },
    {
      "id": "b22d2d1be4cf",
      "title": "The founder conference built for growth: TechCrunch Founder Summit pass rates increase June 26",
      "url": "https://techcrunch.com/2026/06/22/the-founder-conference-built-for-growth-techcrunch-founder-summit-pass-rates-increase-june-26/",
      "source": "TechCrunch",
      "source_type": "news",
      "published": "2026-06-22T14:00:00+00:00",
      "summary": "Save up to $190 on your pass to TechCrunch Founder Summit 2026 by June 26, 11:59 p.m. PT. Designed for founders first on November 4 in Boston. Register today.",
      "category": "Big Tech News",
      "color": "#0d9488"
    },
    {
      "id": "cdb8885aa824",
      "title": "Nvidia Halos",
      "url": "https://www.nvidia.com/en-us/ai-trust-center/halos/autonomous-vehicles/",
      "source": "Hacker News",
      "source_type": "community",
      "published": "2026-06-22T13:57:49+00:00",
      "summary": "⬆ 53 points · 27 comments on Hacker News",
      "category": "Big Tech News",
      "color": "#ff6600"
    },
    {
      "id": "6403de463dad",
      "title": "Moebius: 0.2B image inpainting model with 10B-level performance",
      "url": "https://hustvl.github.io/Moebius/",
      "source": "Hacker News",
      "source_type": "community",
      "published": "2026-06-22T13:53:02+00:00",
      "summary": "⬆ 288 points · 69 comments on Hacker News",
      "category": "Models & Research",
      "color": "#ff6600"
    },
    {
      "id": "d3ee689571cc",
      "title": "PP-OCRv6 on Hugging Face: 50-Language OCR from 1.5M to 34.5M Parameters",
      "url": "https://huggingface.co/blog/PaddlePaddle/pp-ocrv6",
      "source": "Hugging Face",
      "source_type": "company",
      "published": "2026-06-22T13:18:56+00:00",
      "summary": "",
      "category": "Models & Research",
      "color": "#e9a800"
    },
    {
      "id": "71579f365502",
      "title": "At ISC, JUPITER Shows What Exascale Science Looks Like",
      "url": "https://blogs.nvidia.com/blog/jupiter-exascale-supercomputing-science/",
      "source": "NVIDIA",
      "source_type": "company",
      "published": "2026-06-22T13:00:48+00:00",
      "summary": "JUPITER, Europe’s first exascale supercomputer at Germany’s Forschungszentrum Jülich, runs on NVIDIA Grace Hopper Superchips and NVIDIA Quantum-X800 InfiniBand networking — and it’s had a busy year. As the international supercomputing community gathers at ISC in Hamburg this w...",
      "category": "Policy & Safety",
      "color": "#76b900"
    },
    {
      "id": "76f7edffd489",
      "title": "NAIRR Science Program Reshapes Scientific Research, Powered by NVIDIA AI Infrastructure",
      "url": "https://blogs.nvidia.com/blog/nairr-scientific-research-ai-infrastructure/",
      "source": "NVIDIA",
      "source_type": "company",
      "published": "2026-06-22T13:00:38+00:00",
      "summary": "For the past two years, the U.S. National Science Foundation’s National Artificial Intelligence Research Resource (NAIRR) pilot program has driven innovative research across the U.S. for over 700 projects — spanning protein prediction and infectious disease outbreak management...",
      "category": "Tools & Stack",
      "color": "#76b900"
    },
    {
      "id": "2ace5aa8e79c",
      "title": "NVIDIA Vera CPU Opens the Way for Agentic Scientific AI at Los Alamos National Laboratory",
      "url": "https://blogs.nvidia.com/blog/nvidia-vera-cpu-los-alamos-national-laboratory/",
      "source": "NVIDIA",
      "source_type": "company",
      "published": "2026-06-22T13:00:20+00:00",
      "summary": "Mission, Vision and Veritas — new Los Alamos National Laboratory (LANL) supercomputers to be built with HPE and NVIDIA — are tapping NVIDIA Vera CPUs to accelerate scientific discovery, unlocking agentic AI for science. The supercomputers will use the HPE Cray Supercomputing G...",
      "category": "Big Tech News",
      "color": "#76b900"
    },
    {
      "id": "e98fab613985",
      "title": "From Materials Simulation to Experimental Astronomy, New NVIDIA AI Software Unlocks Scientific Discoveries",
      "url": "https://blogs.nvidia.com/blog/ai-for-science-software-cuda/",
      "source": "NVIDIA",
      "source_type": "company",
      "published": "2026-06-22T13:00:20+00:00",
      "summary": "At the ISC conference running in Hamburg this week, NVIDIA is introducing new software that speeds AI for science, from chemistry and materials discovery to the search for dark matter. The NVIDIA DAQIRI library and new NVIDIA ALCHEMI NIM microservices — as well as the NVIDIA c...",
      "category": "Tools & Stack",
      "color": "#76b900"
    },
    {
      "id": "5593704f03db",
      "title": "Eco Wave Power Turns Waves Into Watts With NVIDIA AI Infrastructure and Digital Twins",
      "url": "https://blogs.nvidia.com/blog/eco-wave-power-ai-digital-twins/",
      "source": "NVIDIA",
      "source_type": "company",
      "published": "2026-06-22T13:00:13+00:00",
      "summary": "The next era of AI will not be defined by compute alone. Its growth will be determined by energy. As accelerated computing scales across AI factories, agentic AI, industrial AI, edge computing and physical AI — including robotics and autonomous systems — global electricity dem...",
      "category": "Tools & Stack",
      "color": "#76b900"
    },
    {
      "id": "7e4268ecef5a",
      "title": "The Download: record-breaking subsea tunnels and flexible data centers",
      "url": "https://www.technologyreview.com/2026/06/22/1139385/the-download-rogfast-subsea-tunnel-flexible-data-centers/",
      "source": "MIT Tech Review",
      "source_type": "news",
      "published": "2026-06-22T12:10:00+00:00",
      "summary": "This is todays edition of The Download, our weekday newsletter that provides a daily dose of whats going on in the world of technology. Inside the world’s deepest and longest subsea road tunnel —Niall Firth I’m currently around 1,000 feet beneath the North Sea, in a dark, dank...",
      "category": "Big Tech News",
      "color": "#b91c1c"
    },
    {
      "id": "5d9de7a5a94a",
      "title": "Daybreak: Tools for securing every organization in the world",
      "url": "https://openai.com/index/daybreak-securing-the-world",
      "source": "OpenAI",
      "source_type": "company",
      "published": "2026-06-22T10:00:00+00:00",
      "summary": "OpenAI introduces new Daybreak tools, including Codex Security and GPT-5.5-Cyber, to help organizations find, validate, and patch vulnerabilities at scale.",
      "category": "Models & Research",
      "color": "#10a37f"
    },
    {
      "id": "f601b26b225b",
      "title": "Patch the Planet: a Daybreak initiative to support open source maintainers",
      "url": "https://openai.com/index/patch-the-planet",
      "source": "OpenAI",
      "source_type": "company",
      "published": "2026-06-22T10:00:00+00:00",
      "summary": "OpenAI introduces Patch the Planet, a Daybreak initiative helping open-source maintainers find, validate, and fix vulnerabilities with AI and expert review.",
      "category": "Tools & Stack",
      "color": "#10a37f"
    },
    {
      "id": "bb053c7468c4",
      "title": "Some Electricians Think Building Data Centers Is for Sellouts",
      "url": "https://www.wired.com/story/data-center-buildout-electricians-selling-out/",
      "source": "Wired",
      "source_type": "news",
      "published": "2026-06-22T09:30:00+00:00",
      "summary": "Big Tech is throwing big money into data center buildouts. As national opposition to the facilities grows, some workers are beginning to question whether it’s worth it.",
      "category": "Big Tech News",
      "color": "#6b7280"
    },
    {
      "id": "23d401c189d5",
      "title": "World Cup Scams Are Getting Harder to Spot",
      "url": "https://www.wired.com/story/world-cup-scams-are-getting-harder-to-spot/",
      "source": "Wired",
      "source_type": "news",
      "published": "2026-06-22T09:30:00+00:00",
      "summary": "From fake tickets to cloned websites, AI is magnifying World Cup scams. Can fans distinguish between what’s real and what’s not?",
      "category": "Big Tech News",
      "color": "#6b7280"
    },
    {
      "id": "15e05676a55e",
      "title": "Inside the world’s deepest and longest subsea road tunnel",
      "url": "https://www.technologyreview.com/2026/06/22/1138821/inside-worlds-deepest-longest-subsea-road-tunnel/",
      "source": "MIT Tech Review",
      "source_type": "news",
      "published": "2026-06-22T08:00:00+00:00",
      "summary": "It’s cold, it’s very, very noisy, and—if I can be quite honest with you—I’m not feeling super relaxed. I’m currently around 300 meters, or 1,000 feet, beneath the North Sea, in a dark, dank cave. It smells weird. And I am increasingly aware of the pressure from millions of ton...",
      "category": "Funding & Business",
      "color": "#b91c1c"
    },
    {
      "id": "02ca09e10163",
      "title": "Hotter Than a Hot Tub: The 45°C Breakthrough to Cool AI’s Biggest Machines",
      "url": "https://blogs.nvidia.com/blog/liquid-cooling-ai-factories/",
      "source": "NVIDIA",
      "source_type": "company",
      "published": "2026-06-22T05:00:22+00:00",
      "summary": "Hot tubs sit at about 38 to 40 degrees Celsius, warm enough that most people can only soak for about 15 minutes. NVIDIA’s newest AI servers can run their cooling liquid even hotter — up to 45 degrees Celsius, or 113 degrees Fahrenheit. That higher temperature limit is precisel...",
      "category": "Big Tech News",
      "color": "#76b900"
    },
    {
      "id": "0cd966d46598",
      "title": "Danish privacy activist Lars Andersen raided by police",
      "url": "https://twitter.com/LarsAnders1620/status/2068208864747540516#m",
      "source": "Hacker News",
      "source_type": "community",
      "published": "2026-06-22T04:50:26+00:00",
      "summary": "⬆ 366 points · 327 comments on Hacker News",
      "category": "Big Tech News",
      "color": "#ff6600"
    },
    {
      "id": "5edb7201b0cb",
      "title": "Codex-maxxing for long-running work",
      "url": "https://openai.com/index/codex-maxxing-long-running-work",
      "source": "OpenAI",
      "source_type": "company",
      "published": "2026-06-22T00:00:00+00:00",
      "summary": "Learn how Jason Liu uses Codex to preserve context, manage complex projects, and help work continue beyond a single prompt.",
      "category": "Big Tech News",
      "color": "#10a37f"
    },
    {
      "id": "4af30edd2b4f",
      "title": "We got local models to triage the OpenClaw repo for FREE!*",
      "url": "https://huggingface.co/blog/local-models-pr-triage",
      "source": "Hugging Face",
      "source_type": "company",
      "published": "2026-06-22T00:00:00+00:00",
      "summary": "",
      "category": "Models & Research",
      "color": "#e9a800"
    },
    {
      "id": "663d872622a3",
      "title": "Samsung Electronics brings ChatGPT and Codex to employees",
      "url": "https://openai.com/index/samsung-electronics-chatgpt-codex-deployment",
      "source": "OpenAI",
      "source_type": "company",
      "published": "2026-06-21T23:00:00+00:00",
      "summary": "Samsung Electronics deploys ChatGPT Enterprise and Codex to employees worldwide, marking one of OpenAI’s largest enterprise AI rollouts.",
      "category": "Models & Research",
      "color": "#10a37f"
    },
    {
      "id": "963a38bbce8b",
      "title": "Good results fine tuning a local LLM like Qwen 3:0.6B to categorize questions",
      "url": "https://www.teachmecoolstuff.com/viewarticle/fine-tuning-a-local-llm-to-categorize-questions",
      "source": "Hacker News",
      "source_type": "community",
      "published": "2026-06-21T22:55:23+00:00",
      "summary": "⬆ 195 points · 37 comments on Hacker News",
      "category": "Models & Research",
      "color": "#ff6600"
    },
    {
      "id": "ea5a45c3af5b",
      "title": "Apertus – Open Foundation Model for Sovereign AI",
      "url": "https://apertvs.ai/",
      "source": "Hacker News",
      "source_type": "community",
      "published": "2026-06-21T21:29:43+00:00",
      "summary": "⬆ 523 points · 180 comments on Hacker News",
      "category": "Models & Research",
      "color": "#ff6600"
    },
    {
      "id": "57a790565b60",
      "title": "Show HN: Recall – Local project memory for Claude Code",
      "url": "https://github.com/raiyanyahya/recall",
      "source": "Hacker News",
      "source_type": "community",
      "published": "2026-06-21T21:05:37+00:00",
      "summary": "⬆ 124 points · 74 comments on Hacker News",
      "category": "Models & Research",
      "color": "#ff6600"
    },
    {
      "id": "9ab140b948c2",
      "title": "JSON-LD explained for personal websites",
      "url": "https://hawksley.dev/blog/json-ld-explained-for-personal-websites/",
      "source": "Hacker News",
      "source_type": "community",
      "published": "2026-06-21T18:51:47+00:00",
      "summary": "⬆ 260 points · 84 comments on Hacker News",
      "category": "Big Tech News",
      "color": "#ff6600"
    },
    {
      "id": "a96480a97656",
      "title": "When the Trump administration cracks down on Anthropic, who benefits?",
      "url": "https://techcrunch.com/2026/06/21/when-the-trump-administration-cracks-down-on-anthropic-who-benefits/",
      "source": "TechCrunch",
      "source_type": "news",
      "published": "2026-06-21T15:28:17+00:00",
      "summary": "On the new episode of Equity, we discussed what actually prompted the administration's latest moves against Anthropic, and what this might mean for the AI ecosystem.",
      "category": "Big Tech News",
      "color": "#0d9488"
    },
    {
      "id": "b893e7b70421",
      "title": "Beyond Siri: Here are the practical AI features coming to your iPhone in iOS 27",
      "url": "https://techcrunch.com/2026/06/21/beyond-siri-here-are-the-practical-ai-features-coming-to-your-iphone-in-ios-27/",
      "source": "TechCrunch",
      "source_type": "news",
      "published": "2026-06-21T14:40:28+00:00",
      "summary": "Siri’s AI overhaul may have grabbed the headlines at WWDC, but some of Apple’s most useful AI features are arriving elsewhere in iOS 27.",
      "category": "Big Tech News",
      "color": "#0d9488"
    },
    {
      "id": "ead6b93e0511",
      "title": "Identity verification on Claude",
      "url": "https://support.claude.com/en/articles/14328960-identity-verification-on-claude",
      "source": "Hacker News",
      "source_type": "community",
      "published": "2026-06-21T12:44:13+00:00",
      "summary": "⬆ 828 points · 689 comments on Hacker News",
      "category": "Models & Research",
      "color": "#ff6600"
    },
    {
      "id": "f7a0139ea9bc",
      "title": "28 Tips to Take Your ChatGPT Prompts to the Next Level",
      "url": "https://www.wired.com/story/28-tips-to-take-your-chatgpt-prompts-to-the-next-level/",
      "source": "Wired",
      "source_type": "news",
      "published": "2026-06-21T10:30:00+00:00",
      "summary": "Sure, anyone can use OpenAI’s chatbot. But with smart engineering, you can get way more interesting results.",
      "category": "Models & Research",
      "color": "#6b7280"
    },
    {
      "id": "940826b703b4",
      "title": "Polymarket has flooded social media with deceptive videos by paid creators",
      "url": "https://www.wsj.com/business/media/polymarket-social-media-bets-prediction-market-441cdeb5?st=HhTZY2",
      "source": "Hacker News",
      "source_type": "community",
      "published": "2026-06-21T01:12:21+00:00",
      "summary": "⬆ 269 points · 204 comments on Hacker News",
      "category": "Big Tech News",
      "color": "#ff6600"
    }
  ]
};
