// AI Trend Tracker — auto-generated 2026-06-22 21:12:50
// DO NOT edit manually — re-run fetch_ai_news.py to refresh
const ARTICLES_DATA = {
  "last_updated": "2026-06-22T15:42:50.369993+00:00",
  "total": 145,
  "articles": [
    {
      "id": "f857e1a7ef48",
      "title": "I built Ponytrail, a local audit trail for AI coding-agent edits",
      "url": "https://github.com/0xroylee/ponytrail",
      "source": "Hacker News",
      "source_type": "community",
      "published": "2026-06-22T14:54:59+00:00",
      "summary": "⬆ 15 points · 6 comments on Hacker News",
      "category": "Big Tech News",
      "color": "#ff6600"
    },
    {
      "id": "1a9a5cdd9372",
      "title": "China is having another AI moment",
      "url": "https://www.economist.com/china/2026/06/21/china-is-having-another-ai-moment",
      "source": "Hacker News",
      "source_type": "community",
      "published": "2026-06-22T14:30:47+00:00",
      "summary": "⬆ 8 points · 2 comments on Hacker News",
      "category": "Big Tech News",
      "color": "#ff6600"
    },
    {
      "id": "d509f232d163",
      "title": "Claude Code's \"extended thinking\" is a summary- not authentic thinking",
      "url": "https://patrickmccanna.net/the-text-in-claude-codes-extended-thinking-output-is-not-authentic/",
      "source": "Hacker News",
      "source_type": "community",
      "published": "2026-06-22T14:22:46+00:00",
      "summary": "⬆ 73 points · 52 comments on Hacker News",
      "category": "Models & Research",
      "color": "#ff6600"
    },
    {
      "id": "cdb8885aa824",
      "title": "Nvidia Halos",
      "url": "https://www.nvidia.com/en-us/ai-trust-center/halos/autonomous-vehicles/",
      "source": "Hacker News",
      "source_type": "community",
      "published": "2026-06-22T13:57:49+00:00",
      "summary": "⬆ 44 points · 21 comments on Hacker News",
      "category": "Big Tech News",
      "color": "#ff6600"
    },
    {
      "id": "6403de463dad",
      "title": "Moebius: 0.2B image inpainting model with 10B-level performance",
      "url": "https://hustvl.github.io/Moebius/",
      "source": "Hacker News",
      "source_type": "community",
      "published": "2026-06-22T13:53:02+00:00",
      "summary": "⬆ 46 points · 6 comments on Hacker News",
      "category": "Models & Research",
      "color": "#ff6600"
    },
    {
      "id": "b22d2d1be4cf",
      "title": "The founder conference built for growth: TechCrunch Founder Summit pass rates increase June 26",
      "url": "https://techcrunch.com/2026/06/22/the-founder-conference-built-for-growth-techcrunch-founder-summit-pass-rates-increase-june-26/",
      "source": "TechCrunch",
      "source_type": "news",
      "published": "2026-06-22T08:30:00+00:00",
      "summary": "Save up to $190 on your pass to TechCrunch Founder Summit 2026 by June 26, 11:59 p.m. PT. Designed for founders first on November 4 in Boston. Register here.",
      "category": "Big Tech News",
      "color": "#0d9488"
    },
    {
      "id": "d3ee689571cc",
      "title": "PP-OCRv6 on Hugging Face: 50-Language OCR from 1.5M to 34.5M Parameters",
      "url": "https://huggingface.co/blog/PaddlePaddle/pp-ocrv6",
      "source": "Hugging Face",
      "source_type": "company",
      "published": "2026-06-22T07:48:56+00:00",
      "summary": "",
      "category": "Models & Research",
      "color": "#e9a800"
    },
    {
      "id": "71579f365502",
      "title": "At ISC, JUPITER Shows What Exascale Science Looks Like",
      "url": "https://blogs.nvidia.com/blog/jupiter-exascale-supercomputing-science/",
      "source": "NVIDIA",
      "source_type": "company",
      "published": "2026-06-22T07:30:48+00:00",
      "summary": "JUPITER, Europe’s first exascale supercomputer at Germany’s Forschungszentrum Jülich, runs on NVIDIA Grace Hopper Superchips and NVIDIA Quantum-X800 InfiniBand networking — and it’s had a busy year. As the international supercomputing community gathers at ISC in Hamburg this w...",
      "category": "Policy & Safety",
      "color": "#76b900"
    },
    {
      "id": "76f7edffd489",
      "title": "NAIRR Science Program Reshapes Scientific Research, Powered by NVIDIA AI Infrastructure",
      "url": "https://blogs.nvidia.com/blog/nairr-scientific-research-ai-infrastructure/",
      "source": "NVIDIA",
      "source_type": "company",
      "published": "2026-06-22T07:30:38+00:00",
      "summary": "For the past two years, the U.S. National Science Foundation’s National Artificial Intelligence Research Resource (NAIRR) pilot program has driven innovative research across the U.S. for over 700 projects — spanning protein prediction and infectious disease outbreak management...",
      "category": "Tools & Stack",
      "color": "#76b900"
    },
    {
      "id": "e98fab613985",
      "title": "From Materials Simulation to Experimental Astronomy, New NVIDIA AI Software Unlocks Scientific Discoveries",
      "url": "https://blogs.nvidia.com/blog/ai-for-science-software-cuda/",
      "source": "NVIDIA",
      "source_type": "company",
      "published": "2026-06-22T07:30:20+00:00",
      "summary": "At the ISC conference running in Hamburg this week, NVIDIA is introducing new software that speeds AI for science, from chemistry and materials discovery to the search for dark matter. The NVIDIA DAQIRI library and new NVIDIA ALCHEMI NIM microservices — as well as the NVIDIA c...",
      "category": "Tools & Stack",
      "color": "#76b900"
    },
    {
      "id": "2ace5aa8e79c",
      "title": "NVIDIA Vera CPU Opens the Way for Agentic Scientific AI at Los Alamos National Laboratory",
      "url": "https://blogs.nvidia.com/blog/nvidia-vera-cpu-los-alamos-national-laboratory/",
      "source": "NVIDIA",
      "source_type": "company",
      "published": "2026-06-22T07:30:20+00:00",
      "summary": "Mission, Vision and Veritas — new Los Alamos National Laboratory (LANL) supercomputers to be built with HPE and NVIDIA — are tapping NVIDIA Vera CPUs to accelerate scientific discovery, unlocking agentic AI for science. The supercomputers will use the HPE Cray Supercomputing G...",
      "category": "Big Tech News",
      "color": "#76b900"
    },
    {
      "id": "5593704f03db",
      "title": "Eco Wave Power Turns Waves Into Watts With NVIDIA AI Infrastructure and Digital Twins",
      "url": "https://blogs.nvidia.com/blog/eco-wave-power-ai-digital-twins/",
      "source": "NVIDIA",
      "source_type": "company",
      "published": "2026-06-22T07:30:13+00:00",
      "summary": "The next era of AI will not be defined by compute alone. Its growth will be determined by energy. As accelerated computing scales across AI factories, agentic AI, industrial AI, edge computing and physical AI — including robotics and autonomous systems — global electricity dem...",
      "category": "Tools & Stack",
      "color": "#76b900"
    },
    {
      "id": "7e4268ecef5a",
      "title": "The Download: record-breaking subsea tunnels and flexible data centers",
      "url": "https://www.technologyreview.com/2026/06/22/1139385/the-download-rogfast-subsea-tunnel-flexible-data-centers/",
      "source": "MIT Tech Review",
      "source_type": "news",
      "published": "2026-06-22T06:40:00+00:00",
      "summary": "This is todays edition of The Download, our weekday newsletter that provides a daily dose of whats going on in the world of technology. Inside the world’s deepest and longest subsea road tunnel —Niall Firth I’m currently around 1,000 feet beneath the North Sea, in a dark, dank...",
      "category": "Big Tech News",
      "color": "#b91c1c"
    },
    {
      "id": "0cd966d46598",
      "title": "Danish privacy activist Lars Andersen raided by police",
      "url": "https://twitter.com/LarsAnders1620/status/2068208864747540516#m",
      "source": "Hacker News",
      "source_type": "community",
      "published": "2026-06-22T04:50:26+00:00",
      "summary": "⬆ 360 points · 322 comments on Hacker News",
      "category": "Big Tech News",
      "color": "#ff6600"
    },
    {
      "id": "bb053c7468c4",
      "title": "Some Electricians Think Building Data Centers Is for Sellouts",
      "url": "https://www.wired.com/story/data-center-buildout-electricians-selling-out/",
      "source": "Wired",
      "source_type": "news",
      "published": "2026-06-22T04:00:00+00:00",
      "summary": "Big Tech is throwing big money into data center buildouts. As national opposition to the facilities grows, some workers are beginning to question whether it’s worth it.",
      "category": "Big Tech News",
      "color": "#6b7280"
    },
    {
      "id": "23d401c189d5",
      "title": "World Cup Scams Are Getting Harder to Spot",
      "url": "https://www.wired.com/story/world-cup-scams-are-getting-harder-to-spot/",
      "source": "Wired",
      "source_type": "news",
      "published": "2026-06-22T04:00:00+00:00",
      "summary": "From fake tickets to cloned websites, AI is magnifying World Cup scams. Can fans distinguish between what’s real and what’s not?",
      "category": "Big Tech News",
      "color": "#6b7280"
    },
    {
      "id": "15e05676a55e",
      "title": "Inside the world’s deepest and longest subsea road tunnel",
      "url": "https://www.technologyreview.com/2026/06/22/1138821/inside-worlds-deepest-longest-subsea-road-tunnel/",
      "source": "MIT Tech Review",
      "source_type": "news",
      "published": "2026-06-22T02:30:00+00:00",
      "summary": "It’s cold, it’s very, very noisy, and—if I can be quite honest with you—I’m not feeling super relaxed. I’m currently around 300 meters, or 1,000 feet, beneath the North Sea, in a dark, dank cave. It smells weird. And I am increasingly aware of the pressure from millions of ton...",
      "category": "Funding & Business",
      "color": "#b91c1c"
    },
    {
      "id": "02ca09e10163",
      "title": "Hotter Than a Hot Tub: The 45°C Breakthrough to Cool AI’s Biggest Machines",
      "url": "https://blogs.nvidia.com/blog/liquid-cooling-ai-factories/",
      "source": "NVIDIA",
      "source_type": "company",
      "published": "2026-06-21T23:30:22+00:00",
      "summary": "Hot tubs sit at about 38 to 40 degrees Celsius, warm enough that most people can only soak for about 15 minutes. NVIDIA’s newest AI servers can run their cooling liquid even hotter — up to 45 degrees Celsius, or 113 degrees Fahrenheit. That higher temperature limit is precisel...",
      "category": "Big Tech News",
      "color": "#76b900"
    },
    {
      "id": "963a38bbce8b",
      "title": "Good results fine tuning a local LLM like Qwen 3:0.6B to categorize questions",
      "url": "https://www.teachmecoolstuff.com/viewarticle/fine-tuning-a-local-llm-to-categorize-questions",
      "source": "Hacker News",
      "source_type": "community",
      "published": "2026-06-21T22:55:23+00:00",
      "summary": "⬆ 191 points · 37 comments on Hacker News",
      "category": "Models & Research",
      "color": "#ff6600"
    },
    {
      "id": "ea5a45c3af5b",
      "title": "Apertus – Open Foundation Model for Sovereign AI",
      "url": "https://apertvs.ai/",
      "source": "Hacker News",
      "source_type": "community",
      "published": "2026-06-21T21:29:43+00:00",
      "summary": "⬆ 490 points · 165 comments on Hacker News",
      "category": "Models & Research",
      "color": "#ff6600"
    },
    {
      "id": "57a790565b60",
      "title": "Show HN: Recall – Local project memory for Claude Code",
      "url": "https://github.com/raiyanyahya/recall",
      "source": "Hacker News",
      "source_type": "community",
      "published": "2026-06-21T21:05:37+00:00",
      "summary": "⬆ 124 points · 74 comments on Hacker News",
      "category": "Models & Research",
      "color": "#ff6600"
    },
    {
      "id": "9ab140b948c2",
      "title": "JSON-LD explained for personal websites",
      "url": "https://hawksley.dev/blog/json-ld-explained-for-personal-websites/",
      "source": "Hacker News",
      "source_type": "community",
      "published": "2026-06-21T18:51:47+00:00",
      "summary": "⬆ 259 points · 84 comments on Hacker News",
      "category": "Big Tech News",
      "color": "#ff6600"
    },
    {
      "id": "663d872622a3",
      "title": "Samsung Electronics brings ChatGPT and Codex to employees",
      "url": "https://openai.com/index/samsung-electronics-chatgpt-codex-deployment",
      "source": "OpenAI",
      "source_type": "company",
      "published": "2026-06-21T17:30:00+00:00",
      "summary": "Samsung Electronics deploys ChatGPT Enterprise and Codex to employees worldwide, marking one of OpenAI’s largest enterprise AI rollouts.",
      "category": "Models & Research",
      "color": "#10a37f"
    },
    {
      "id": "ead6b93e0511",
      "title": "Identity verification on Claude",
      "url": "https://support.claude.com/en/articles/14328960-identity-verification-on-claude",
      "source": "Hacker News",
      "source_type": "community",
      "published": "2026-06-21T12:44:13+00:00",
      "summary": "⬆ 827 points · 689 comments on Hacker News",
      "category": "Models & Research",
      "color": "#ff6600"
    },
    {
      "id": "a96480a97656",
      "title": "When the Trump administration cracks down on Anthropic, who benefits?",
      "url": "https://techcrunch.com/2026/06/21/when-the-trump-administration-cracks-down-on-anthropic-who-benefits/",
      "source": "TechCrunch",
      "source_type": "news",
      "published": "2026-06-21T09:58:17+00:00",
      "summary": "On the new episode of Equity, we discussed what actually prompted the administration's latest moves against Anthropic, and what this might mean for the AI ecosystem.",
      "category": "Big Tech News",
      "color": "#0d9488"
    },
    {
      "id": "b893e7b70421",
      "title": "Beyond Siri: Here are the practical AI features coming to your iPhone in iOS 27",
      "url": "https://techcrunch.com/2026/06/21/beyond-siri-here-are-the-practical-ai-features-coming-to-your-iphone-in-ios-27/",
      "source": "TechCrunch",
      "source_type": "news",
      "published": "2026-06-21T09:10:28+00:00",
      "summary": "Siri’s AI overhaul may have grabbed the headlines at WWDC, but some of Apple’s most useful AI features are arriving elsewhere in iOS 27.",
      "category": "Big Tech News",
      "color": "#0d9488"
    },
    {
      "id": "f7a0139ea9bc",
      "title": "28 Tips to Take Your ChatGPT Prompts to the Next Level",
      "url": "https://www.wired.com/story/28-tips-to-take-your-chatgpt-prompts-to-the-next-level/",
      "source": "Wired",
      "source_type": "news",
      "published": "2026-06-21T05:00:00+00:00",
      "summary": "Sure, anyone can use OpenAI’s chatbot. But with smart engineering, you can get way more interesting results.",
      "category": "Models & Research",
      "color": "#6b7280"
    },
    {
      "id": "1492a9b71b79",
      "title": "The Wholesale Plagiarism of Obscure Sorrows",
      "url": "https://waxy.org/2026/06/the-wholesale-plagiarism-of-obscure-sorrows/",
      "source": "Hacker News",
      "source_type": "community",
      "published": "2026-06-20T18:05:31+00:00",
      "summary": "⬆ 280 points · 117 comments on Hacker News",
      "category": "Big Tech News",
      "color": "#ff6600"
    },
    {
      "id": "7ddc78b7ede2",
      "title": "Signal’s Meredith Whittaker wants you to remember that AI chatbots ‘are not your friends’",
      "url": "https://techcrunch.com/2026/06/20/signals-meredith-whittaker-wants-you-to-remember-that-ai-chatbots-are-not-your-friends/",
      "source": "TechCrunch",
      "source_type": "news",
      "published": "2026-06-20T15:02:29+00:00",
      "summary": "\"These are not your friends. These are not conscious beings. These are not sentient interlocutors.”",
      "category": "Big Tech News",
      "color": "#0d9488"
    },
    {
      "id": "a5dce2d46468",
      "title": "US Scientist John Jumper to Leave Google DeepMind for Anthropic",
      "url": "https://www.reuters.com/technology/us-scientist-john-jumper-leave-google-deepmind-anthropic-2026-06-19/",
      "source": "Hacker News",
      "source_type": "community",
      "published": "2026-06-20T14:32:15+00:00",
      "summary": "⬆ 63 points · 8 comments on Hacker News",
      "category": "Big Tech News",
      "color": "#ff6600"
    },
    {
      "id": "18e2c6cc1f43",
      "title": "Ubisoft co-founder Claude Guillemot has died in a plane crash",
      "url": "https://www.reuters.com/world/ubisofts-co-founder-claude-guillemot-dies-plane-crash-2026-06-20/",
      "source": "Hacker News",
      "source_type": "community",
      "published": "2026-06-20T14:12:50+00:00",
      "summary": "⬆ 142 points · 84 comments on Hacker News",
      "category": "Models & Research",
      "color": "#ff6600"
    },
    {
      "id": "5cab6cb8b0ba",
      "title": "In the Weights is your new AI-centric vanity search",
      "url": "https://techcrunch.com/2026/06/20/in-the-weights-is-your-new-ai-centric-vanity-search/",
      "source": "TechCrunch",
      "source_type": "news",
      "published": "2026-06-20T14:11:11+00:00",
      "summary": "So ... what's your In the Weights score?",
      "category": "Big Tech News",
      "color": "#0d9488"
    },
    {
      "id": "a856726d0c43",
      "title": "Show HN: We post-trained a model that pen tests instead of refusing",
      "url": "https://www.argusred.com/cli",
      "source": "Hacker News",
      "source_type": "community",
      "published": "2026-06-20T13:49:03+00:00",
      "summary": "⬆ 52 points · 25 comments on Hacker News",
      "category": "Models & Research",
      "color": "#ff6600"
    },
    {
      "id": "d5b7ef8aa299",
      "title": "Race Against Time to Save Brixton Market from Private Equity",
      "url": "https://novaramedia.com/2026/06/19/race-against-time-to-save-brixton-market-from-private-equity/",
      "source": "Hacker News",
      "source_type": "community",
      "published": "2026-06-20T12:01:50+00:00",
      "summary": "⬆ 16 points · 1 comments on Hacker News",
      "category": "Big Tech News",
      "color": "#ff6600"
    },
    {
      "id": "528d0e934f25",
      "title": "Temporary Cloudflare accounts for AI agents",
      "url": "https://blog.cloudflare.com/temporary-accounts/",
      "source": "Hacker News",
      "source_type": "community",
      "published": "2026-06-20T11:19:05+00:00",
      "summary": "⬆ 133 points · 83 comments on Hacker News",
      "category": "Big Tech News",
      "color": "#ff6600"
    },
    {
      "id": "232b0ce5ea49",
      "title": "Nobel laureate John Jumper is leaving DeepMind for rival Anthropic",
      "url": "https://techcrunch.com/2026/06/20/nobel-laureate-john-jumper-is-leaving-deepmind-for-rival-anthropic/",
      "source": "TechCrunch",
      "source_type": "news",
      "published": "2026-06-20T11:09:57+00:00",
      "summary": "Jumper isn't the only big name leaving Google DeepMind.",
      "category": "Big Tech News",
      "color": "#0d9488"
    },
    {
      "id": "d4d3a88923a6",
      "title": "Bootimus – A Self-Contained PXE and HTTP Boot Server",
      "url": "https://bootimus.com",
      "source": "Hacker News",
      "source_type": "community",
      "published": "2026-06-20T10:55:18+00:00",
      "summary": "⬆ 98 points · 36 comments on Hacker News",
      "category": "Big Tech News",
      "color": "#ff6600"
    },
    {
      "id": "977190f7106d",
      "title": "Siri AI Hands On: A Smart, Helpful Assistant",
      "url": "https://www.wired.com/story/siri-ai-hands-on-iphone/",
      "source": "Wired",
      "source_type": "news",
      "published": "2026-06-20T04:30:00+00:00",
      "summary": "The new Siri AI is conversational, omnipresent, and actually helpful.",
      "category": "Big Tech News",
      "color": "#6b7280"
    },
    {
      "id": "f0aaa00764d7",
      "title": "LLMs Are Complicated Now",
      "url": "https://ianbarber.blog/2026/06/19/llms-are-complicated-now/",
      "source": "Hacker News",
      "source_type": "community",
      "published": "2026-06-20T01:25:14+00:00",
      "summary": "⬆ 155 points · 56 comments on Hacker News",
      "category": "Models & Research",
      "color": "#ff6600"
    },
    {
      "id": "d0d9430b3e14",
      "title": "From PGP to Mythos: a brief history of export controls that didn’t stop anyone",
      "url": "https://techcrunch.com/2026/06/19/encryption-spyware-and-now-mythos-history-shows-why-cyber-export-control-doesnt-work/",
      "source": "TechCrunch",
      "source_type": "news",
      "published": "2026-06-19T17:10:14+00:00",
      "summary": "For the last 30 years, stopping the flow of cybersecurity-related software has proven to be ineffective. It's unclear why it would work now with Anthropic’s cybersecurity model Mythos.",
      "category": "Models & Research",
      "color": "#0d9488"
    },
    {
      "id": "359a8d1c31d4",
      "title": "Hyundai buys Boston Dynamics",
      "url": "https://startupfortune.com/hyundai-takes-full-control-of-boston-dynamics-as-softbank-exits-for-325-million/",
      "source": "Hacker News",
      "source_type": "community",
      "published": "2026-06-19T16:28:20+00:00",
      "summary": "⬆ 924 points · 388 comments on Hacker News",
      "category": "Big Tech News",
      "color": "#ff6600"
    },
    {
      "id": "89a83bf2a75c",
      "title": "GPT-5.5 hallucinates 3x more than MIT-licensed GLM-5.2",
      "url": "https://arrowtsx.dev/bigger-models/",
      "source": "Hacker News",
      "source_type": "community",
      "published": "2026-06-19T16:11:25+00:00",
      "summary": "⬆ 483 points · 240 comments on Hacker News",
      "category": "Models & Research",
      "color": "#ff6600"
    },
    {
      "id": "299189fcbd81",
      "title": "Munich 1991: The Roots of the Current AI Boom",
      "url": "https://people.idsia.ch/~juergen/ai-boom-roots-munich-1991.html",
      "source": "Hacker News",
      "source_type": "community",
      "published": "2026-06-19T15:54:23+00:00",
      "summary": "⬆ 163 points · 70 comments on Hacker News",
      "category": "Big Tech News",
      "color": "#ff6600"
    },
    {
      "id": "d131d924d4b8",
      "title": "Is the US government’s Anthropic ban accidentally helping the brand?",
      "url": "https://techcrunch.com/video/is-the-us-governments-anthropic-ban-accidentally-helping-the-brand/",
      "source": "TechCrunch",
      "source_type": "news",
      "published": "2026-06-19T10:38:17+00:00",
      "summary": "Just as last weekwas ending,the US governmentforced Anthropic to pull its two newest models, Fable 5 and Mythos 5, citing national security concerns after Amazon researchers allegedly found a way to bypass Fable 5s guardrails. Cybersecurity researchers havesince signed an open...",
      "category": "Models & Research",
      "color": "#0d9488"
    },
    {
      "id": "00841429d7c1",
      "title": "The US banned Anthropic’s Fable 5 release, but the numbers don’t seem to care",
      "url": "https://techcrunch.com/podcast/the-us-banned-anthropics-fable-5-release-but-the-numbers-dont-seem-to-care/",
      "source": "TechCrunch",
      "source_type": "news",
      "published": "2026-06-19T10:31:03+00:00",
      "summary": "Just as last weekwas ending,the US governmentforced Anthropic to pull its two newest models, Fable 5 and Mythos 5, citing national security concerns after Amazon researchers allegedly found a way to bypass Fable 5s guardrails. Cybersecurity researchers havesince signed an open...",
      "category": "Models & Research",
      "color": "#0d9488"
    },
    {
      "id": "e35040ffdf08",
      "title": "Billionaire Ambani wants AI in every call, app, and home",
      "url": "https://techcrunch.com/2026/06/19/billionaire-ambani-wants-ai-in-every-call-app-and-home/",
      "source": "TechCrunch",
      "source_type": "news",
      "published": "2026-06-19T09:53:28+00:00",
      "summary": "Reliance is weaving AI into telecom services used by more than 500 million people.",
      "category": "Funding & Business",
      "color": "#0d9488"
    },
    {
      "id": "26573a4dcd11",
      "title": "Introducing Web Search on Amazon Bedrock AgentCore",
      "url": "https://aws.amazon.com/blogs/machine-learning/introducing-web-search-on-amazon-bedrock-agentcore/",
      "source": "AWS ML",
      "source_type": "company",
      "published": "2026-06-19T08:45:24+00:00",
      "summary": "Web Search on Amazon Bedrock AgentCore is now generally available. In this post, we walk through what makes Web Search on Amazon Bedrock AgentCore different, why it matters, and how to wire it in with a few lines of code.",
      "category": "Big Tech News",
      "color": "#ff9900"
    },
    {
      "id": "ff2487fd34ed",
      "title": "Accelerate campaign workflow with insights from Adobe Marketing Agent for Amazon Quick",
      "url": "https://aws.amazon.com/blogs/machine-learning/accelerate-campaign-workflow-with-insights-from-adobe-marketing-agent-for-amazon-quick/",
      "source": "AWS ML",
      "source_type": "company",
      "published": "2026-06-19T08:35:04+00:00",
      "summary": "This post shows how to enable Adobe Marketing Agent for Amazon Quick using a Model Context Protocol (MCP). We walk you through how to configure the integration, authenticate using your Adobe credentials, and get the latest insights in Amazon Quick. The sample workflow returns ...",
      "category": "Models & Research",
      "color": "#ff9900"
    },
    {
      "id": "076b29791c7a",
      "title": "The CEO of Allbirds’ new AI biz has a plan. Now she needs a “brand-new team”",
      "url": "https://techcrunch.com/2026/06/19/the-ceo-of-allbirds-new-ai-biz-has-a-plan-but-no-employees/",
      "source": "TechCrunch",
      "source_type": "news",
      "published": "2026-06-19T07:30:00+00:00",
      "summary": "Call it a startup with a sole founder and a very large seed round, but what's next is less clear.",
      "category": "Funding & Business",
      "color": "#0d9488"
    },
    {
      "id": "229a5a6ccdc1",
      "title": "The Download: AI bottleneck debates, and BCI trials take off",
      "url": "https://www.technologyreview.com/2026/06/19/1139327/the-download-llms-bottleneck-breakthrough-bci-trials-take-off/",
      "source": "MIT Tech Review",
      "source_type": "news",
      "published": "2026-06-19T06:40:00+00:00",
      "summary": "This is todays edition of The Download, our weekday newsletter that provides a daily dose of whats going on in the world of technology. A startup claims it broke through a bottleneck that’s holding back LLMs AI startup Subquadratic came out of stealth last month with a huge cl...",
      "category": "Models & Research",
      "color": "#b91c1c"
    },
    {
      "id": "8add01e4aff7",
      "title": "A startup claims it broke through a bottleneck that’s holding back LLMs",
      "url": "https://www.technologyreview.com/2026/06/19/1139313/a-startup-claims-it-broke-through-a-bottleneck-thats-holding-back-llms/",
      "source": "MIT Tech Review",
      "source_type": "news",
      "published": "2026-06-19T05:10:24+00:00",
      "summary": "The Miami-based AI startup Subquadratic came out of stealth mode last month with a huge claim. It announced that it had solved a mathematical bottleneck that had been holding back large language models for almost a decade. The details were thin, and many people were unconvince...",
      "category": "Models & Research",
      "color": "#b91c1c"
    },
    {
      "id": "3a1b32087c0f",
      "title": "The inevitable weakness of metrics",
      "url": "https://www.technologyreview.com/2026/06/19/1138778/inevitable-weakness-metrics-quantified-life-book-review/",
      "source": "MIT Tech Review",
      "source_type": "news",
      "published": "2026-06-19T03:30:00+00:00",
      "summary": "There are plenty of useful things a metric can reveal. There are even more it can obscure or corrupt. It took me well over a decade of tracking my own life in ever greater detail to fully appreciate this duality, which probably reveals something about both me and the nature of...",
      "category": "Big Tech News",
      "color": "#b91c1c"
    },
    {
      "id": "183efb0ffed1",
      "title": "Brain-computer interface trials are taking off",
      "url": "https://www.technologyreview.com/2026/06/19/1139270/brain-computer-interface-trials-are-taking-off/",
      "source": "MIT Tech Review",
      "source_type": "news",
      "published": "2026-06-19T03:30:00+00:00",
      "summary": "This week, I covered the story of Casey Harrell—a man with ALS who is “the first power user” of a brain implant, according to the researchers who worked with him. Harrell is paralyzed and unable to speak coherently without the device. He has now spent almost three years using ...",
      "category": "Big Tech News",
      "color": "#b91c1c"
    },
    {
      "id": "bd33e41be4e5",
      "title": "The US says ASML’s top chip tool may be in China, but how?",
      "url": "https://techcrunch.com/2026/06/19/the-us-says-asmls-top-chip-tool-may-be-in-china-asml-says-it-isnt/",
      "source": "TechCrunch",
      "source_type": "news",
      "published": "2026-06-19T02:29:12+00:00",
      "summary": "There's a commercial logic that cuts against the idea that ASML would risk its export license to arm a Chinese customer.",
      "category": "Tools & Stack",
      "color": "#0d9488"
    },
    {
      "id": "f7db370cf36f",
      "title": "Source: Elastic agrees to buy CRV-backed Deductive AI for up to $85M",
      "url": "https://techcrunch.com/2026/06/18/source-elastic-agrees-to-buy-crv-backed-deductiveai-for-up-to-85m/",
      "source": "TechCrunch",
      "source_type": "news",
      "published": "2026-06-18T19:21:11+00:00",
      "summary": "Deductive AI, a startup that uses AI to catch and resolve bugs in software, was founded just three years ago.",
      "category": "Funding & Business",
      "color": "#0d9488"
    },
    {
      "id": "0c0c29d9b936",
      "title": "Monitor and debug generative AI inference with SageMaker detailed metrics and Insights dashboard on CloudWatch",
      "url": "https://aws.amazon.com/blogs/machine-learning/monitor-and-debug-generative-ai-inference-with-sagemaker-detailed-metrics-and-insights-dashboard-on-cloudwatch/",
      "source": "AWS ML",
      "source_type": "company",
      "published": "2026-06-18T18:01:58+00:00",
      "summary": "Amazon SageMaker AI provides fully managed real-time inference hosting for machine learning models. You deploy a model to a SageMaker endpoint backed by one or more compute instances, and SageMaker handles provisioning and scaling. SageMaker supports multiple endpoint architec...",
      "category": "Models & Research",
      "color": "#ff9900"
    },
    {
      "id": "95f3b8c0bab9",
      "title": "Microsoft discovers new lightweight backdoor that steals cryptocurrency",
      "url": "https://arstechnica.com/security/2026/06/microsoft-spots-new-self-propagating-malware-for-stealing-cryptocurrency/",
      "source": "Ars Technica",
      "source_type": "news",
      "published": "2026-06-18T17:58:52+00:00",
      "summary": "Crypto Clipper spreads over USB and communicates over Tor.",
      "category": "Big Tech News",
      "color": "#ff6600"
    },
    {
      "id": "ffd482a186da",
      "title": "How the Peter Thiel-Linked Dialog Club Secretly Ranks Its Members",
      "url": "https://www.wired.com/story/how-peter-thiels-private-dialog-club-secretly-ranks-its-members/",
      "source": "Wired",
      "source_type": "news",
      "published": "2026-06-18T16:42:45+00:00",
      "summary": "Leaked files show the invite-only network grades members by their money and fame, shaping who’s in, who’s out, and who pays.",
      "category": "Big Tech News",
      "color": "#6b7280"
    },
    {
      "id": "c7f03eb380cc",
      "title": "AI inference startup Baseten reportedly raising $1.5B months after its last mega-round",
      "url": "https://techcrunch.com/2026/06/18/ai-inference-startup-baseten-reportedly-raising-1-5b-months-after-its-last-mega-round/",
      "source": "TechCrunch",
      "source_type": "news",
      "published": "2026-06-18T15:50:13+00:00",
      "summary": "Startup Baseten is reportedly close to finalizing a $1.5 billion round at a $13 billion as the “inference gold rush\" marches on.",
      "category": "Tools & Stack",
      "color": "#0d9488"
    },
    {
      "id": "683dcb58db1d",
      "title": "The White House Is Making Up Its Rules for AI in Real Time",
      "url": "https://www.wired.com/story/anthropic-mythos-export-controls-ai-regulations/",
      "source": "Wired",
      "source_type": "news",
      "published": "2026-06-18T15:33:43+00:00",
      "summary": "Anthropic still can’t distribute Claude Mythos or Fable 5 after running afoul of the Trump administration. But no one can say exactly what the company did wrong.",
      "category": "Models & Research",
      "color": "#6b7280"
    },
    {
      "id": "8fd795d8c6da",
      "title": "Snap spins off AI video team into new company, Dotmo, due to costs",
      "url": "https://techcrunch.com/2026/06/18/snap-spins-off-ai-video-team-into-new-company-dotmo-due-to-costs/",
      "source": "TechCrunch",
      "source_type": "news",
      "published": "2026-06-18T15:00:00+00:00",
      "summary": "The Snapchat maker is spinning off yet another internal unit. Dotmo will be composed of current Snap staff who are leaving the social media company to focus on AI video development.",
      "category": "Big Tech News",
      "color": "#0d9488"
    },
    {
      "id": "fdfac61152ca",
      "title": "How FERC’s Large-Load Interconnection Actions Help Address Grid Stress, Improve Affordability",
      "url": "https://blogs.nvidia.com/blog/ferc-large-load-interconnection/",
      "source": "NVIDIA",
      "source_type": "company",
      "published": "2026-06-18T14:30:27+00:00",
      "summary": "In a consequential grid infrastructure decision, the Federal Energy Regulatory Commission (FERC) today issued a major milestone on large-load interconnection impacting how those building AI factories, semiconductor fabrication support systems and advanced manufacturing facilit...",
      "category": "Real-world AI Use",
      "color": "#76b900"
    },
    {
      "id": "a628c0f8d3b5",
      "title": "Apple patches high-severity eavesdropping vulnerability in Beats Studio Buds",
      "url": "https://arstechnica.com/apple/2026/06/apple-patches-high-severity-eavesdropping-vulnerability-in-beats-studio-buds/",
      "source": "Ars Technica",
      "source_type": "news",
      "published": "2026-06-18T14:11:35+00:00",
      "summary": "The vulnerability, disclosed 12 months ago, affects multiple manufacturers.",
      "category": "Big Tech News",
      "color": "#ff6600"
    },
    {
      "id": "1cce7fb422fb",
      "title": "Meta’s AI Workers Are Revolting, Peter Thiel’s Secret Society, and SBF’s Plea to Trump",
      "url": "https://www.wired.com/story/uncanny-valley-podcast-meta-ai-workers-revolting-peter-thiel-secret-society-sbf-plea-to-trump/",
      "source": "Wired",
      "source_type": "news",
      "published": "2026-06-18T13:59:51+00:00",
      "summary": "On today’s Uncanny Valley, we dive into the dysfunction in Meta’s newly formed AI unit and why it’s been driving already-low employee morale even further into the ground.",
      "category": "Big Tech News",
      "color": "#6b7280"
    },
    {
      "id": "63333d90a8a4",
      "title": "MosaicLeaks: Can your research agent keep a secret?",
      "url": "https://huggingface.co/blog/ServiceNow/mosaicleaks",
      "source": "Hugging Face",
      "source_type": "company",
      "published": "2026-06-18T12:43:13+00:00",
      "summary": "",
      "category": "Big Tech News",
      "color": "#e9a800"
    },
    {
      "id": "c2ccfa8440be",
      "title": "Before SpaceX IPO, investors in China secretly acquired stakes",
      "url": "https://arstechnica.com/information-technology/2026/06/before-spacex-ipo-investors-in-china-secretly-acquired-stakes/",
      "source": "Ars Technica",
      "source_type": "news",
      "published": "2026-06-18T12:12:18+00:00",
      "summary": "One previously unreported SpaceX investor has ties to Chinese military contractors.",
      "category": "Funding & Business",
      "color": "#ff6600"
    },
    {
      "id": "d8e63c5da78e",
      "title": "Amazon Bedrock AgentCore harness is now generally available: Go from idea to production-grade agent in minutes",
      "url": "https://aws.amazon.com/blogs/machine-learning/amazon-bedrock-agentcore-harness-is-now-generally-available-go-from-idea-to-production-grade-agent-in-minutes/",
      "source": "AWS ML",
      "source_type": "company",
      "published": "2026-06-18T12:02:22+00:00",
      "summary": "Today, Amazon Bedrock AgentCore harness is generally available. Two API calls (CreateHarness to define an agent, and InvokeHarness to run it), and you have an agent running in seconds. The agent runs in its own isolated environment with a filesystem and shell, so it can read f...",
      "category": "Real-world AI Use",
      "color": "#ff9900"
    },
    {
      "id": "a55ebd412e31",
      "title": "New usage analytics and updated spend controls for enterprises",
      "url": "https://openai.com/index/chatgpt-enterprise-spend-controls",
      "source": "OpenAI",
      "source_type": "company",
      "published": "2026-06-18T11:30:00+00:00",
      "summary": "OpenAI introduces new spend controls and usage analytics for ChatGPT Enterprise, helping organizations manage costs and scale AI with confidence.",
      "category": "Models & Research",
      "color": "#10a37f"
    },
    {
      "id": "e323a1edc540",
      "title": "3 Amazon Workers Say They’re Under Investigation for Speaking Out About Data Centers",
      "url": "https://www.wired.com/story/amazon-workers-under-internal-investigation-after-speaking-out-about-data-centers/",
      "source": "Wired",
      "source_type": "news",
      "published": "2026-06-18T10:33:27+00:00",
      "summary": "The software engineers filed a complaint with Seattle’s civil rights office accusing Amazon of illegally retaliating against them for expressing their personal political beliefs.",
      "category": "Real-world AI Use",
      "color": "#6b7280"
    },
    {
      "id": "878e03f0bb5b",
      "title": "At Cannes Lions, NVIDIA Partners Reshape Advertising and Marketing With AI",
      "url": "https://blogs.nvidia.com/blog/nvidia-ai-marketing-advertising-cannes-lions/",
      "source": "NVIDIA",
      "source_type": "company",
      "published": "2026-06-18T07:30:43+00:00",
      "summary": "The digital era gave the advertising and marketing industry speed; the AI era is giving it autonomous operations. For companies building next-generation technologies for advertising and marketing, the question is no longer whether to adopt AI but whether their infrastructure c...",
      "category": "Tools & Stack",
      "color": "#76b900"
    },
    {
      "id": "e1a1021043ec",
      "title": "Sync and Stream: GeForce NOW Connects to Members’ Game Libraries Across Devices",
      "url": "https://blogs.nvidia.com/blog/geforce-now-thursday-game-stores/",
      "source": "NVIDIA",
      "source_type": "company",
      "published": "2026-06-18T07:30:32+00:00",
      "summary": "Play favorite titles from popular game libraries, keep progress synced and jump back into gaming sessions on virtually any device. That’s the power of GeForce NOW cloud gaming. From providing access to members’ favorite game libraries to offering some of the season’s best memb...",
      "category": "Big Tech News",
      "color": "#76b900"
    },
    {
      "id": "3d684ebde5de",
      "title": "The Download: a new hunt for dark matter and Kenya’s case for going solar",
      "url": "https://www.technologyreview.com/2026/06/18/1139261/the-download-dark-matter-hunt-kenya-solar-power/",
      "source": "MIT Tech Review",
      "source_type": "news",
      "published": "2026-06-18T06:40:00+00:00",
      "summary": "This is todays edition of The Download, our weekday newsletter that provides a daily dose of whats going on in the world of technology. The search for dark matter has been blown wide open For decades, physicists have hunted for weakly interacting massive particles (WIMPs), a l...",
      "category": "Big Tech News",
      "color": "#b91c1c"
    },
    {
      "id": "ad2ec02b5ba7",
      "title": "Improving health intelligence in ChatGPT",
      "url": "https://openai.com/index/improving-health-intelligence-in-chatgpt",
      "source": "OpenAI",
      "source_type": "company",
      "published": "2026-06-18T05:30:00+00:00",
      "summary": "Learn how GPT-5.5 Instant improves ChatGPT’s health and wellness responses with stronger reasoning, better context, clearer communication, and physician-informed evaluations.",
      "category": "Models & Research",
      "color": "#10a37f"
    },
    {
      "id": "a828121842cb",
      "title": "Geoengineering still faces major practical challenges",
      "url": "https://www.technologyreview.com/2026/06/18/1139227/geoengineering-engineering-challenges/",
      "source": "MIT Tech Review",
      "source_type": "news",
      "published": "2026-06-18T04:30:00+00:00",
      "summary": "Solar geoengineering is often portrayed as a sort of emergency brake. Something along the lines of Pull in case of climate emergency to scatter light-reflecting particles to bounce sunlight out of the atmosphere and cool the planet. But it might be less like a simple brake and...",
      "category": "Real-world AI Use",
      "color": "#b91c1c"
    },
    {
      "id": "125b40f286ef",
      "title": "The search for dark matter has been blown wide open",
      "url": "https://www.technologyreview.com/2026/06/18/1138755/search-for-dark-matter-blown-wide-open/",
      "source": "MIT Tech Review",
      "source_type": "news",
      "published": "2026-06-18T03:30:00+00:00",
      "summary": "Underneath an Apennine massif, below the Jinping Mountains of Sichuan, and at the bottom of a South Dakota mine, there is a cosmic hunt afoot. Isolated deep beneath these rocky shields, massive detectors filled with liquid xenon aim to make the first direct detections of dark ...",
      "category": "Big Tech News",
      "color": "#b91c1c"
    },
    {
      "id": "796b3536965e",
      "title": "Using AI to help physicians diagnose rare genetic diseases affecting children",
      "url": "https://openai.com/index/diagnose-rare-childhood-diseases",
      "source": "OpenAI",
      "source_type": "company",
      "published": "2026-06-18T02:30:00+00:00",
      "summary": "Researchers used an OpenAI reasoning model to help diagnose rare diseases, identifying 18 new diagnoses in previously unsolved cases.",
      "category": "Models & Research",
      "color": "#10a37f"
    },
    {
      "id": "4751d22d2888",
      "title": "France Advances Europe’s AI Future With NVIDIA Technologies",
      "url": "https://blogs.nvidia.com/blog/france-advances-europes-ai-future/",
      "source": "NVIDIA",
      "source_type": "company",
      "published": "2026-06-18T00:30:59+00:00",
      "summary": "A year ago at NVIDIA GTC Paris at VivaTech, France laid out plans to advance local AI — from new AI factories and national compute capacity to open frontier models and industrial platforms. Now, that AI infrastructure is coming online. AI agents are running in production, star...",
      "category": "Models & Research",
      "color": "#76b900"
    },
    {
      "id": "e10f10a21b2f",
      "title": "The UK Will Scan Asylum-Seekers’ Faces for Age Checks—Despite Knowing the Tech Is Flawed",
      "url": "https://www.wired.com/story/facial-age-estimate-uk-asylum-seekers/",
      "source": "Wired",
      "source_type": "news",
      "published": "2026-06-18T00:30:00+00:00",
      "summary": "Internal Home Office tests of age-verification technology show the risks of life-altering errors. It’s moving forward anyway.",
      "category": "Policy & Safety",
      "color": "#6b7280"
    },
    {
      "id": "904542d363ce",
      "title": "Now You Don't: When Espionage Meets Magic",
      "url": "https://www.politicshome.com/news/article/now-dont-espionage-meets-magic",
      "source": "Hacker News",
      "source_type": "community",
      "published": "2026-06-17T20:15:57+00:00",
      "summary": "⬆ 20 points · 2 comments on Hacker News",
      "category": "Big Tech News",
      "color": "#ff6600"
    },
    {
      "id": "a84ffebb319e",
      "title": "Beyond LoRA: Can you beat the most popular fine-tuning technique?",
      "url": "https://huggingface.co/blog/peft-beyond-lora",
      "source": "Hugging Face",
      "source_type": "company",
      "published": "2026-06-17T18:30:00+00:00",
      "summary": "",
      "category": "Models & Research",
      "color": "#e9a800"
    },
    {
      "id": "91c11face685",
      "title": "Is it agentic enough? Benchmarking open models on your own tooling",
      "url": "https://huggingface.co/blog/is-it-agentic-enough",
      "source": "Hugging Face",
      "source_type": "company",
      "published": "2026-06-17T18:30:00+00:00",
      "summary": "",
      "category": "Models & Research",
      "color": "#e9a800"
    },
    {
      "id": "5a5ce2d394ba",
      "title": "The Korean Telecom Giant at the Center of Anthropic’s Mythos Controversy",
      "url": "https://www.wired.com/story/sk-telecom-anthropic-mythos-export-controls/",
      "source": "Wired",
      "source_type": "news",
      "published": "2026-06-17T17:22:00+00:00",
      "summary": "Days before Anthropic took its most advanced AI models offline, the White House ordered the company to revoke SK Telecom’s access to Claude Mythos over claims of alleged ties to China.",
      "category": "Models & Research",
      "color": "#6b7280"
    },
    {
      "id": "dc82cd34b6f2",
      "title": "Amazon SageMaker AI Async Inference now supports inline request payloads",
      "url": "https://aws.amazon.com/blogs/machine-learning/amazon-sagemaker-ai-async-inference-now-supports-inline-request-payloads/",
      "source": "AWS ML",
      "source_type": "company",
      "published": "2026-06-17T15:26:36+00:00",
      "summary": "Today, we’re announcing inline payload support for Amazon SageMaker AI Async Inference. Customers can now send inference payloads directly in the request body of the InvokeEndpointAsync API, removing the need to upload input data to Amazon Simple Storage Service (Amazon S3) be...",
      "category": "Tools & Stack",
      "color": "#ff9900"
    },
    {
      "id": "b70a9cc5481d",
      "title": "Get back hours every day with autonomous agents in Amazon Quick",
      "url": "https://aws.amazon.com/blogs/machine-learning/get-back-hours-every-day-with-autonomous-agents-in-amazon-quick/",
      "source": "AWS ML",
      "source_type": "company",
      "published": "2026-06-17T15:05:39+00:00",
      "summary": "Today, Quick gets even more powerful: new autonomous agents that work continuously&nbsp;on your behalf,&nbsp;an activity feed that helps you prioritize your most important work, and the ability to&nbsp;find insights&nbsp;across every data source your business runs on from a si...",
      "category": "Big Tech News",
      "color": "#ff9900"
    },
    {
      "id": "cfd72d92bffb",
      "title": "Massive breach spills credentials for thousands of sensitive networks",
      "url": "https://arstechnica.com/security/2026/06/massive-breach-spills-credentials-for-thousands-of-sensitive-networks/",
      "source": "Ars Technica",
      "source_type": "news",
      "published": "2026-06-17T14:24:31+00:00",
      "summary": "The affected include Oracle, Lenovo, FedEx, a NATO contractor, and Fortinet.",
      "category": "Big Tech News",
      "color": "#ff6600"
    },
    {
      "id": "c767b5e1d460",
      "title": "Tesco moving 40,000 server workloads off VMware amid Broadcom's “abusive conduct”",
      "url": "https://arstechnica.com/information-technology/2026/06/tesco-moving-40000-server-workloads-off-vmware-amid-broadcoms-abusive-conduct/",
      "source": "Ars Technica",
      "source_type": "news",
      "published": "2026-06-17T14:13:13+00:00",
      "summary": "Tesco claimed Broadcom hiked its VMware prices by about 175 percent in UK court filings.",
      "category": "Big Tech News",
      "color": "#ff6600"
    },
    {
      "id": "c8ead1490bde",
      "title": "Operating a Humanoid With Your Body Is a Hot Job in China’s Hardware Capital",
      "url": "https://www.wired.com/story/humanoid-robot-training-in-chinas-hardware-capital/",
      "source": "Wired",
      "source_type": "news",
      "published": "2026-06-17T12:55:35+00:00",
      "summary": "In Shenzhen, workers at IO-AI Tech control humanoid robots using a VR rig reminiscent of Ready Player One.",
      "category": "Big Tech News",
      "color": "#6b7280"
    },
    {
      "id": "8b2d013a0637",
      "title": "\"Dangerous\" AI models are coming no matter what",
      "url": "https://arstechnica.com/ai/2026/06/dangerous-ai-models-are-coming-no-matter-what/",
      "source": "Ars Technica",
      "source_type": "news",
      "published": "2026-06-17T12:20:46+00:00",
      "summary": "AI models with advanced hacking capabilities will soon be the norm.",
      "category": "Models & Research",
      "color": "#ff6600"
    },
    {
      "id": "05b5229437ee",
      "title": "Context intelligence for your data and AI agents at scale",
      "url": "https://aws.amazon.com/blogs/machine-learning/context-intelligence-for-your-data-and-ai-agents-at-scale/",
      "source": "AWS ML",
      "source_type": "company",
      "published": "2026-06-17T11:47:37+00:00",
      "summary": "Agents are only as intelligent as the context they can reason over. Today, that context is scattered across data lakes, data warehouses, lakehouses, databases, and streams, and in institutional knowledge that has never been written down. You want to trust the decisions made by...",
      "category": "Big Tech News",
      "color": "#ff9900"
    },
    {
      "id": "5c3d0274acbe",
      "title": "The White House Wants Anthropic to Block All Jailbreaks. That May Not Be Possible",
      "url": "https://www.wired.com/story/the-white-house-wants-anthropic-to-block-all-jailbreaks-that-may-not-be-possible/",
      "source": "Wired",
      "source_type": "news",
      "published": "2026-06-17T11:30:00+00:00",
      "summary": "Trump administration officials tell WIRED that if Anthropic wants to rerelease Fable 5, it will need to ensure the model's guardrails can't be circumvented. Security experts say that can't be done.",
      "category": "Models & Research",
      "color": "#6b7280"
    },
    {
      "id": "f9bf6f21a126",
      "title": "New in Amazon Bedrock AgentCore: Build agents with broader knowledge and continuous learning",
      "url": "https://aws.amazon.com/blogs/machine-learning/new-in-amazon-bedrock-agentcore-build-agents-with-broader-knowledge-and-continuous-learning/",
      "source": "AWS ML",
      "source_type": "company",
      "published": "2026-06-17T09:59:36+00:00",
      "summary": "Today we're introducing new capabilities on Amazon Bedrock AgentCore, the platform to build, connect, and optimize agents. In this post, we cover how these capabilities close each gap: connecting agents to organizational, web, and paid knowledge; helping teams find and fix wha...",
      "category": "Tools & Stack",
      "color": "#ff9900"
    },
    {
      "id": "4630c466154f",
      "title": "MolmoMotion: Language-guided 3D motion forecasting",
      "url": "https://huggingface.co/blog/allenai/molmomotion",
      "source": "Hugging Face",
      "source_type": "company",
      "published": "2026-06-17T09:56:44+00:00",
      "summary": "",
      "category": "Big Tech News",
      "color": "#e9a800"
    },
    {
      "id": "0af1478cb097",
      "title": "New research shows how AMIE, our medical AI, could help manage health conditions.",
      "url": "https://blog.google/innovation-and-ai/models-and-research/google-research/amie-for-disease-management-in-nature/",
      "source": "Google AI",
      "source_type": "company",
      "published": "2026-06-17T09:30:00+00:00",
      "summary": "Research in “Nature” shows our conversational AI system matches primary care physicians in complex disease management.",
      "category": "Big Tech News",
      "color": "#4285f4"
    },
    {
      "id": "7c8cd3e9533a",
      "title": "The Gemini-Powered Google Home Speaker Is Finally Here",
      "url": "https://www.wired.com/story/the-gemini-powered-google-home-speaker-is-finally-here/",
      "source": "Wired",
      "source_type": "news",
      "published": "2026-06-17T07:30:00+00:00",
      "summary": "Arriving six years after Google’s last smart speaker, the new HomePod-style device was redesigned to play host to Gemini’s chatbot.",
      "category": "Models & Research",
      "color": "#6b7280"
    },
    {
      "id": "049cb7f55b5d",
      "title": "The Download: a reality check for geoengineering and the science of interoception",
      "url": "https://www.technologyreview.com/2026/06/17/1139200/the-download-solar-geoengineering-interoception/",
      "source": "MIT Tech Review",
      "source_type": "news",
      "published": "2026-06-17T06:40:00+00:00",
      "summary": "This is todays edition of The Download, our weekday newsletter that provides a daily dose of whats going on in the world of technology. Hacking the atmosphere: geoengineering gets a reality check Solar geoengineering, the controversial idea that we could deliberately intervene...",
      "category": "Big Tech News",
      "color": "#b91c1c"
    },
    {
      "id": "ba1da3c3a07b",
      "title": "Windows and Linux users: The deadline to update Secure Boot keys is near",
      "url": "https://arstechnica.com/security/2026/06/windows-and-linux-users-the-deadline-to-update-secure-boot-keys-is-near/",
      "source": "Ars Technica",
      "source_type": "news",
      "published": "2026-06-17T05:45:17+00:00",
      "summary": "What you need to know about the expiration of keys securing your machine's boot sequence.",
      "category": "Big Tech News",
      "color": "#ff6600"
    },
    {
      "id": "f8bb7a9443cc",
      "title": "From the Hugging Face Hub to robot hardware with Strands Agents and LeRobot",
      "url": "https://huggingface.co/blog/amazon/strands-lerobot-hub-to-hardware",
      "source": "Hugging Face",
      "source_type": "company",
      "published": "2026-06-17T04:48:05+00:00",
      "summary": "",
      "category": "Big Tech News",
      "color": "#e9a800"
    },
    {
      "id": "80c1a32658b0",
      "title": "A near-autonomous AI chemist improves a challenging reaction in medicinal chemistry",
      "url": "https://openai.com/index/ai-chemist-improves-reaction",
      "source": "OpenAI",
      "source_type": "company",
      "published": "2026-06-17T04:30:00+00:00",
      "summary": "OpenAI and Molecule.one show how a near-autonomous AI chemist using GPT-5.4 improved a key drug-making reaction, advancing medicinal chemistry research.",
      "category": "Models & Research",
      "color": "#10a37f"
    },
    {
      "id": "d36e8bce9456",
      "title": "GLM-5.2: Built for Long-Horizon Tasks",
      "url": "https://huggingface.co/blog/zai-org/glm-52-blog",
      "source": "Hugging Face",
      "source_type": "company",
      "published": "2026-06-17T03:31:25+00:00",
      "summary": "",
      "category": "Big Tech News",
      "color": "#e9a800"
    },
    {
      "id": "db9922117603",
      "title": "Entrepreneurs in Nairobi make the case for going solar",
      "url": "https://www.technologyreview.com/2026/06/17/1138600/entrepreneurs-nairobi-case-for-going-solar/",
      "source": "MIT Tech Review",
      "source_type": "news",
      "published": "2026-06-17T03:30:00+00:00",
      "summary": "Most of Kenya’s power grid runs on renewables. But with 25% of communities lacking centralized electricity, the nation is looking to off-grid solar to hit its goal of delivering universal electricity access by 2030 without driving up emissions. The ever-­improving economics of...",
      "category": "Policy & Safety",
      "color": "#b91c1c"
    },
    {
      "id": "8ee7ec35dcf5",
      "title": "Hacking the atmosphere: Geoengineering gets a reality check",
      "url": "https://www.technologyreview.com/2026/06/17/1138743/hacking-atmosphere-geoengineering-reality-check/",
      "source": "MIT Tech Review",
      "source_type": "news",
      "published": "2026-06-17T03:30:00+00:00",
      "summary": "Jim Franke pulls away the cover page of a presentation on the wraparound desk in his office, revealing an illustration of an odd-­looking aircraft with massive wings stretching out from a stubby fuselage. The uncrewed plane is soaring thousands of meters higher than commercial...",
      "category": "Big Tech News",
      "color": "#b91c1c"
    },
    {
      "id": "916e534ab8d5",
      "title": "Introducing LifeSciBench",
      "url": "https://openai.com/index/introducing-life-sci-bench",
      "source": "OpenAI",
      "source_type": "company",
      "published": "2026-06-16T18:30:00+00:00",
      "summary": "Introducing LifeSciBench, an expert-authored, expert-reviewed benchmark for evaluating how AI systems handle real-world life science research tasks and decisions.",
      "category": "Models & Research",
      "color": "#10a37f"
    },
    {
      "id": "4dd2073282fe",
      "title": "Agentic Resource Discovery: Let agents search",
      "url": "https://huggingface.co/blog/agentic-resource-discovery-launch",
      "source": "Hugging Face",
      "source_type": "company",
      "published": "2026-06-16T18:30:00+00:00",
      "summary": "",
      "category": "Big Tech News",
      "color": "#e9a800"
    },
    {
      "id": "621c369bb66f",
      "title": "A 1969 camera operators' strike created Upstairs Downstairs multiverse",
      "url": "https://ironicsans.ghost.io/the-color-strike/",
      "source": "Hacker News",
      "source_type": "community",
      "published": "2026-06-16T18:24:39+00:00",
      "summary": "⬆ 79 points · 24 comments on Hacker News",
      "category": "Big Tech News",
      "color": "#ff6600"
    },
    {
      "id": "7b0b77197773",
      "title": "Safeguard your agentic AI applications with the Amazon Bedrock Guardrails InvokeGuardrailChecks API",
      "url": "https://aws.amazon.com/blogs/machine-learning/safeguard-your-agentic-ai-applications-with-the-amazon-bedrock-guardrails-invokeguardrailchecks-api/",
      "source": "AWS ML",
      "source_type": "company",
      "published": "2026-06-16T17:16:46+00:00",
      "summary": "Today, we’re announcing a new API with Amazon Bedrock Guardrails. With this API, you can apply individual safeguards, also referred to as safety checks, at any point in your agentic AI applications without creating guardrail resources. In this post, we walk through how the Inv...",
      "category": "Tools & Stack",
      "color": "#ff9900"
    },
    {
      "id": "e56087ba39e5",
      "title": "Hands Free, AIs Forward: NVIDIA XR AI Brings Agents to AR Glasses",
      "url": "https://blogs.nvidia.com/blog/nvidia-xr-ai/",
      "source": "NVIDIA",
      "source_type": "company",
      "published": "2026-06-16T17:00:41+00:00",
      "summary": "NVIDIA XR AI is now available in public beta, giving developers a framework for building multimodal AI agents for AR glasses and XR devices.",
      "category": "Models & Research",
      "color": "#76b900"
    },
    {
      "id": "f079545d0a19",
      "title": "Year of free HPE software a “step in the correct direction” in VMware rivalry",
      "url": "https://arstechnica.com/information-technology/2026/06/hpe-tempts-vmware-users-partners-with-year-of-free-virtualization-software/",
      "source": "Ars Technica",
      "source_type": "news",
      "published": "2026-06-16T16:41:15+00:00",
      "summary": "Partner tells Ars that HPE should be giving out more free VM Essentials licenses.",
      "category": "Big Tech News",
      "color": "#ff6600"
    },
    {
      "id": "73f0fe714484",
      "title": "Coherent Breaks Ground on Expanded Texas Facility, Scaling AI’s Optical Backbone",
      "url": "https://blogs.nvidia.com/blog/coherent-texas-ai-optical/",
      "source": "NVIDIA",
      "source_type": "company",
      "published": "2026-06-16T16:40:56+00:00",
      "summary": "AI runs at the speed of light. More and more, that light is made in Texas. Coherent broke ground today on an expanded manufacturing building in Sherman, Texas. The company makes the lasers, optical components and compound semiconductors that wire AI systems together — and runs...",
      "category": "Real-world AI Use",
      "color": "#76b900"
    },
    {
      "id": "a003a9a1e711",
      "title": "Introducing container caching in Amazon SageMaker AI for faster model scaling",
      "url": "https://aws.amazon.com/blogs/machine-learning/introducing-container-caching-in-amazon-sagemaker-ai-for-faster-model-scaling/",
      "source": "AWS ML",
      "source_type": "company",
      "published": "2026-06-16T14:46:02+00:00",
      "summary": "Today, we’re excited to announce container image caching for Amazon SageMaker AI inference, the next major advancement in our faster scaling optimization journey. This speeds up end-to-end latency by up to 2x for generative AI models during scale-out events.",
      "category": "Models & Research",
      "color": "#ff9900"
    },
    {
      "id": "0bf5057db0d1",
      "title": "Parallelize speculative decoding with P-EAGLE on Amazon SageMaker AI",
      "url": "https://aws.amazon.com/blogs/machine-learning/parallelize-speculative-decoding-with-p-eagle-on-amazon-sagemaker-ai/",
      "source": "AWS ML",
      "source_type": "company",
      "published": "2026-06-16T12:17:09+00:00",
      "summary": "This post walks you through how to use P-EAGLE directly within Amazon SageMaker AI. It will demonstrate how to select a compatible model from the SageMaker JumpStart catalog, configure the parallel drafting specifications, and deploy a highly optimized real-time SageMaker AI e...",
      "category": "Models & Research",
      "color": "#ff9900"
    },
    {
      "id": "a8a99da03dcc",
      "title": "HPE AI Factory With NVIDIA Expands for the Era of Agents",
      "url": "https://blogs.nvidia.com/blog/hpe-ai-factory-agentic-enterprise/",
      "source": "NVIDIA",
      "source_type": "company",
      "published": "2026-06-16T11:00:27+00:00",
      "summary": "Enterprises are moving agentic AI from proof of concept to production — and the next generation of AI factories are built for the era of agents. At HPE Discover Las Vegas, running through Thursday, June 18, NVIDIA and HPE are expanding the HPE AI Factory with NVIDIA, including...",
      "category": "Real-world AI Use",
      "color": "#76b900"
    },
    {
      "id": "39294416a114",
      "title": "Fastest, Largest, Strongest: NVIDIA Blackwell Sweeps MLPerf Training 6.0",
      "url": "https://blogs.nvidia.com/blog/blackwell-mlperf-training-6-0/",
      "source": "NVIDIA",
      "source_type": "company",
      "published": "2026-06-16T09:30:36+00:00",
      "summary": "Every breakthrough AI model starts the same way: with a training run. The infrastructure running those training jobs shapes everything: how fast teams can iterate, what scale of model they can build and whether those jobs complete reliably. As models grow in size, complexity a...",
      "category": "Models & Research",
      "color": "#76b900"
    },
    {
      "id": "98586e1b1098",
      "title": "Critical Copilot vulnerability allowed hackers to steal 2FA code from users",
      "url": "https://arstechnica.com/security/2026/06/critical-copilot-vulnerability-allowed-hackers-to-seal-2fa-code-from-users/",
      "source": "Ars Technica",
      "source_type": "news",
      "published": "2026-06-16T05:45:46+00:00",
      "summary": "SearchLeak exploit shows why the industry's approach to LLM security fails over and over.",
      "category": "Models & Research",
      "color": "#ff6600"
    },
    {
      "id": "031fe56c38cf",
      "title": "Predicting model behavior before release by simulating deployment",
      "url": "https://openai.com/index/deployment-simulation",
      "source": "OpenAI",
      "source_type": "company",
      "published": "2026-06-15T18:30:00+00:00",
      "summary": "OpenAI introduces Deployment Simulation, a method to predict AI model behavior before deployment using real conversation data to improve safety and evaluation accuracy.",
      "category": "Models & Research",
      "color": "#10a37f"
    },
    {
      "id": "c0d1dc402103",
      "title": "Introducing Gemma 4 models on Amazon Bedrock",
      "url": "https://aws.amazon.com/blogs/machine-learning/introducing-gemma-4-models-on-amazon-bedrock/",
      "source": "AWS ML",
      "source_type": "company",
      "published": "2026-06-15T14:54:15+00:00",
      "summary": "Today, we are announcing the availability of the Gemma 4 family on Amazon Bedrock. Built by Google DeepMind and released under the Apache 2.0 license, Gemma 4 is a family of open-weight models designed with a focus on intelligence-per-parameter across a broad range of deployme...",
      "category": "Models & Research",
      "color": "#ff9900"
    },
    {
      "id": "67377d6541c6",
      "title": "Users cry foul after AMD stripped memory crypto from its consumer CPUs",
      "url": "https://arstechnica.com/security/2026/06/users-cry-foul-after-amd-stripped-memory-crypto-from-its-consumer-cpus/",
      "source": "Ars Technica",
      "source_type": "news",
      "published": "2026-06-15T12:25:46+00:00",
      "summary": "AMD's stripping of TSME from consumer CPUs appears to be a deliberate, covert move.",
      "category": "Big Tech News",
      "color": "#ff6600"
    },
    {
      "id": "72386a5f1b1c",
      "title": "We’re strengthening our presence in Alabama through new investments and community support.",
      "url": "https://blog.google/innovation-and-ai/infrastructure-and-cloud/global-network/alabama-investment-june-2026/",
      "source": "Google AI",
      "source_type": "company",
      "published": "2026-06-15T09:30:00+00:00",
      "summary": "Google has announced a $1.5 billion investment for 2026 and 2027 to expand its data center campus in Jackson County, Alabama. Operating since 2019 on a repurposed former…",
      "category": "Funding & Business",
      "color": "#4285f4"
    },
    {
      "id": "9b41ef631f1c",
      "title": "Introducing the OpenAI Partner Network",
      "url": "https://openai.com/index/introducing-openai-partner-network",
      "source": "OpenAI",
      "source_type": "company",
      "published": "2026-06-14T11:30:00+00:00",
      "summary": "OpenAI launches the Partner Network, investing $150M to help global partners accelerate enterprise AI adoption, deployment, and transformation.",
      "category": "Big Tech News",
      "color": "#10a37f"
    },
    {
      "id": "6e9cc34dd8c5",
      "title": "PeopleSoft 0-day affecting hundreds of organizations steals gigabytes of data",
      "url": "https://arstechnica.com/security/2026/06/peoplesoft-0-day-affecting-hundreds-of-organizations-steals-gigabytes-of-data/",
      "source": "Ars Technica",
      "source_type": "news",
      "published": "2026-06-12T13:56:47+00:00",
      "summary": "Vulnerability in the Oracle-owned PeopleSoft software is about as critical as they come.",
      "category": "Big Tech News",
      "color": "#ff6600"
    },
    {
      "id": "31e268b2c07a",
      "title": "New OpenAI Academy courses for the next era of work",
      "url": "https://openai.com/index/academy-courses-applying-ai-at-work",
      "source": "OpenAI",
      "source_type": "company",
      "published": "2026-06-12T04:30:00+00:00",
      "summary": "OpenAI introduces three Academy courses that help people build practical AI skills, create repeatable workflows, and apply agents in everyday work.",
      "category": "Real-world AI Use",
      "color": "#10a37f"
    },
    {
      "id": "e5e9bd931104",
      "title": "How Preply combines AI and human tutors to personalize learning",
      "url": "https://openai.com/index/preply",
      "source": "OpenAI",
      "source_type": "company",
      "published": "2026-06-11T18:30:00+00:00",
      "summary": "Preply uses OpenAI to launch AI-generated lesson summaries, providing personalised feedback and language learning exercises.",
      "category": "Big Tech News",
      "color": "#10a37f"
    },
    {
      "id": "a004c2b18314",
      "title": "Our new community investments in Virginia support local jobs and expand energy affordability.",
      "url": "https://blog.google/innovation-and-ai/infrastructure-and-cloud/global-network/virginia-community-investments/",
      "source": "Google AI",
      "source_type": "company",
      "published": "2026-06-11T14:30:00+00:00",
      "summary": "We’re helping build the state’s next-generation workforce and investing in energy programs.",
      "category": "Funding & Business",
      "color": "#4285f4"
    },
    {
      "id": "8926e37d73b8",
      "title": "BBVA puts AI at the core of banking with OpenAI",
      "url": "https://openai.com/index/bbva",
      "source": "OpenAI",
      "source_type": "company",
      "published": "2026-06-10T18:30:00+00:00",
      "summary": "Learn how BBVA scaled ChatGPT Enterprise to 100,000 employees and partnered with OpenAI to accelerate AI-powered banking transformation worldwide.",
      "category": "Models & Research",
      "color": "#10a37f"
    },
    {
      "id": "f5fdb80fa91a",
      "title": "How an astrophysicist uses Codex to help simulate black holes",
      "url": "https://openai.com/index/using-codex-to-simulate-black-holes",
      "source": "OpenAI",
      "source_type": "company",
      "published": "2026-06-10T18:30:00+00:00",
      "summary": "Discover how astrophysicist Chi-kwan Chan uses Codex to build black hole simulations, helping scientists study extreme physics and test Einstein’s theory of general relativity.",
      "category": "Big Tech News",
      "color": "#10a37f"
    },
    {
      "id": "9a812e42d024",
      "title": "Profiling in PyTorch (Part 2): From nn.Linear to a Fused MLP",
      "url": "https://huggingface.co/blog/torch-mlp-fusion",
      "source": "Hugging Face",
      "source_type": "company",
      "published": "2026-06-10T18:30:00+00:00",
      "summary": "",
      "category": "Big Tech News",
      "color": "#e9a800"
    },
    {
      "id": "7d1f3e342dc6",
      "title": "Locked in heated rivalry with researcher, Microsoft fixes 0-day they disclosed",
      "url": "https://arstechnica.com/security/2026/06/locked-in-heated-rivalry-with-researcher-microsoft-fixes-0-day-they-disclosed/",
      "source": "Ars Technica",
      "source_type": "news",
      "published": "2026-06-09T15:26:52+00:00",
      "summary": "A separate zero-day also disclosed by Nightmare Eclipse appears to be patched as well.",
      "category": "Big Tech News",
      "color": "#ff6600"
    },
    {
      "id": "6d8d3867b1f2",
      "title": "How an Agent Built a 3D Paris Gallery by Chaining Two Hugging Face Spaces",
      "url": "https://huggingface.co/blog/mishig/spaces-agents-md",
      "source": "Hugging Face",
      "source_type": "company",
      "published": "2026-06-09T05:16:19+00:00",
      "summary": "",
      "category": "Big Tech News",
      "color": "#e9a800"
    },
    {
      "id": "eb3e2d9f4685",
      "title": "Migrating Your GitHub CI to Hugging Face Jobs",
      "url": "https://huggingface.co/blog/github-ci-hf-jobs",
      "source": "Hugging Face",
      "source_type": "company",
      "published": "2026-06-08T18:30:00+00:00",
      "summary": "",
      "category": "Big Tech News",
      "color": "#e9a800"
    },
    {
      "id": "4cd526a0df04",
      "title": "The Open Source Community is backing OpenEnv for Agentic RL",
      "url": "https://huggingface.co/blog/openenv-agentic-rl",
      "source": "Hugging Face",
      "source_type": "company",
      "published": "2026-06-07T18:30:00+00:00",
      "summary": "",
      "category": "Tools & Stack",
      "color": "#e9a800"
    },
    {
      "id": "752c96ffbdef",
      "title": "The latest AI news we announced in May 2026",
      "url": "https://blog.google/innovation-and-ai/technology/ai/google-ai-updates-may-2026/",
      "source": "Google AI",
      "source_type": "company",
      "published": "2026-06-05T09:15:00+00:00",
      "summary": "May AI recap",
      "category": "Big Tech News",
      "color": "#4285f4"
    },
    {
      "id": "a799e1e611d4",
      "title": "5 ways Google Search can level up your thrift and vintage shopping",
      "url": "https://blog.google/products-and-platforms/products/search/thrifting-tips/",
      "source": "Google AI",
      "source_type": "company",
      "published": "2026-06-03T07:30:00+00:00",
      "summary": "A colorful, grain-textured collage of various items scattered across a light blue background. The items include a green bucket hat, a wooden clothes hanger, a blue-and-red striped collar, blue sunglasses, denim shorts, a yellow price tag, a red high-heele",
      "category": "Big Tech News",
      "color": "#4285f4"
    },
    {
      "id": "4be325886964",
      "title": "How we used Gemini to build Google I/O 2026",
      "url": "https://blog.google/innovation-and-ai/technology/ai/io-2026-google-ai/",
      "source": "Google AI",
      "source_type": "company",
      "published": "2026-06-01T10:30:00+00:00",
      "summary": "A collage of I/O-related images, including the Antigravity Coffee Co. pop-up, a colorful jellyfish and a still from the Timmy TPU video. The word AI repeats three times on the left of the image, and there are colorful icons, including a sparkle, as well.",
      "category": "Models & Research",
      "color": "#4285f4"
    },
    {
      "id": "bb0319888f69",
      "title": "Take our I/O 2026 quiz, vibe coded in Google AI Studio.",
      "url": "https://blog.google/innovation-and-ai/technology/ai/io-2026-vibe-coded-quiz/",
      "source": "Google AI",
      "source_type": "company",
      "published": "2026-05-29T13:30:00+00:00",
      "summary": "We used Google AI Studio to vibe code a quiz about our top I/O 2026 announcements.",
      "category": "Big Tech News",
      "color": "#4285f4"
    },
    {
      "id": "6aee6b02d3b5",
      "title": "9 demos of Gemini Omni and Gemini 3.5 in action",
      "url": "https://blog.google/innovation-and-ai/models-and-research/gemini-models/gemini-omni-3-5-videos/",
      "source": "Google AI",
      "source_type": "company",
      "published": "2026-05-29T12:00:00+00:00",
      "summary": "Gemini Omni & Gemini 3.5 hero",
      "category": "Models & Research",
      "color": "#4285f4"
    },
    {
      "id": "7a1c98af09d2",
      "title": "Check out real-life AI prototypes from the Futures Lab.",
      "url": "https://blog.google/innovation-and-ai/technology/ai/university-waterloo-labs/",
      "source": "Google AI",
      "source_type": "company",
      "published": "2026-05-29T06:30:00+00:00",
      "summary": "University of Waterloo students develop AI prototypes like sign language tutors to reshape the future of education and work.",
      "category": "Real-world AI Use",
      "color": "#4285f4"
    },
    {
      "id": "3404b326f5b4",
      "title": "Catch up on 12 major I/O 2026 moments",
      "url": "https://blog.google/innovation-and-ai/technology/ai/io-2026-keynote-moment-videos/",
      "source": "Google AI",
      "source_type": "company",
      "published": "2026-05-28T09:30:00+00:00",
      "summary": "The colorful I/O logo against a black background, surrounded by stills from the I/O keynote",
      "category": "Big Tech News",
      "color": "#4285f4"
    },
    {
      "id": "18f4f93feb30",
      "title": "Catch up on the Dialogues stage at Google I/O 2026.",
      "url": "https://blog.google/innovation-and-ai/technology/ai/io-2026-dialogues-recap/",
      "source": "Google AI",
      "source_type": "company",
      "published": "2026-05-22T12:30:00+00:00",
      "summary": "Alphabet CEO Sundar Pichai in conversation on the I/O 2026 Dialogues stage",
      "category": "Big Tech News",
      "color": "#4285f4"
    },
    {
      "id": "58130303da4c",
      "title": "We’re announcing new community investments in Missouri.",
      "url": "https://blog.google/innovation-and-ai/infrastructure-and-cloud/global-network/missouri-programs/",
      "source": "Google AI",
      "source_type": "company",
      "published": "2026-05-20T15:10:00+00:00",
      "summary": "We’re helping build the state’s next-generation workforce and investing in energy programs.",
      "category": "Funding & Business",
      "color": "#4285f4"
    },
    {
      "id": "e7785d8c77e3",
      "title": "Google just redesigned the search box for the first time in 25 years — here’s why it matters more than you think.",
      "url": "https://venturebeat.com/technology/google-just-redesigned-the-search-box-for-the-first-time-in-25-years-heres-why-it-matters-more-than-you-think",
      "source": "VentureBeat",
      "source_type": "news",
      "published": "2026-05-19T12:15:00+00:00",
      "summary": "For a quarter century, the Google search box has been one of the most recognizable interfaces in computing: a thin white rectangle, a blinking cursor, a few typed words, and a list of blue links. On Tuesday, Google will formally retire that paradigm.At its annual I/O developer...",
      "category": "Tools & Stack",
      "color": "#7c3aed"
    },
    {
      "id": "e670024b9a32",
      "title": "Railway secures $100 million to challenge AWS with AI-native cloud infrastructure",
      "url": "https://venturebeat.com/infrastructure/railway-secures-usd100-million-to-challenge-aws-with-ai-native-cloud",
      "source": "VentureBeat",
      "source_type": "news",
      "published": "2026-01-22T08:30:00+00:00",
      "summary": "Railway, a San Francisco-based cloud platform that has quietly amassed two million developers without spending a dollar on marketing, announced Thursday that it raised $100 million in a Series B funding round, as surging demand for artificial intelligence applications exposes ...",
      "category": "Tools & Stack",
      "color": "#7c3aed"
    },
    {
      "id": "1bd5d5f60cc3",
      "title": "Claude Code costs up to $200 a month. Goose does the same thing for free.",
      "url": "https://venturebeat.com/infrastructure/claude-code-costs-up-to-usd200-a-month-goose-does-the-same-thing-for-free",
      "source": "VentureBeat",
      "source_type": "news",
      "published": "2026-01-19T08:30:00+00:00",
      "summary": "The artificial intelligence coding revolution comes with a catch: it&#x27;s expensive.Claude Code, Anthropic&#x27;s terminal-based AI agent that can write, debug, and deploy code autonomously, has captured the imagination of software developers worldwide. But its pricing — ran...",
      "category": "Models & Research",
      "color": "#7c3aed"
    },
    {
      "id": "ca731494b194",
      "title": "Listen Labs raises $69M after viral billboard hiring stunt to scale AI customer interviews",
      "url": "https://venturebeat.com/technology/listen-labs-raises-usd69m-after-viral-billboard-hiring-stunt-to-scale-ai",
      "source": "VentureBeat",
      "source_type": "news",
      "published": "2026-01-16T08:31:00+00:00",
      "summary": "Alfred Wahlforss was running out of options. His startup, Listen Labs, needed to hire over 100 engineers, but competing against Mark Zuckerberg&#x27;s $100 million offers seemed impossible. So he spent $5,000 — a fifth of his marketing budget — on a billboard in San Francisco ...",
      "category": "Big Tech News",
      "color": "#7c3aed"
    },
    {
      "id": "db7ff708ed2f",
      "title": "Salesforce rolls out new Slackbot AI agent as it battles Microsoft and Google in workplace AI",
      "url": "https://venturebeat.com/technology/salesforce-rolls-out-new-slackbot-ai-agent-as-it-battles-microsoft-and",
      "source": "VentureBeat",
      "source_type": "news",
      "published": "2026-01-13T07:30:00+00:00",
      "summary": "Salesforce on Tuesday launched an entirely rebuilt version of Slackbot, the company&#x27;s workplace assistant, transforming it from a simple notification tool into what executives describe as a fully powered AI agent capable of searching enterprise data, drafting documents, a...",
      "category": "Real-world AI Use",
      "color": "#7c3aed"
    },
    {
      "id": "a102a18a5efc",
      "title": "Anthropic launches Cowork, a Claude Desktop agent that works in your files — no coding required",
      "url": "https://venturebeat.com/technology/anthropic-launches-cowork-a-claude-desktop-agent-that-works-in-your-files-no",
      "source": "VentureBeat",
      "source_type": "news",
      "published": "2026-01-12T06:00:00+00:00",
      "summary": "Anthropic released Cowork on Monday, a new AI agent capability that extends the power of its wildly successful Claude Code tool to non-technical users — and according to company insiders, the team built the entire feature in approximately a week and a half, largely using Claud...",
      "category": "Models & Research",
      "color": "#7c3aed"
    },
    {
      "id": "b37d93646457",
      "title": "Nous Research's NousCoder-14B is an open-source coding model landing right in the Claude Code moment",
      "url": "https://venturebeat.com/technology/nous-researchs-nouscoder-14b-is-an-open-source-coding-model-landing-right-in",
      "source": "VentureBeat",
      "source_type": "news",
      "published": "2026-01-07T14:30:00+00:00",
      "summary": "Nous Research, the open-source artificial intelligence startup backed by crypto venture firm Paradigm, released a new competitive programming model on Monday that it says matches or exceeds several larger proprietary systems — trained in just four days using 48 of Nvidia&#x27;...",
      "category": "Models & Research",
      "color": "#7c3aed"
    }
  ]
};
